import Database from "better-sqlite3";
import {spawnSync} from "node:child_process";
import {mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join,resolve} from "node:path";
import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {grade6Lessons} from "@/data/curriculum/grade-6/content";
import {grade7Lessons} from "@/data/curriculum/grade-7/content";
import {grade8Lessons} from "@/data/curriculum/grade-8/content";
import {grade9Lessons} from "@/data/curriculum/grade-9/content";
import {grade10BatchAsOf,grade10Lessons,grade10Sources} from "@/data/curriculum/grade-10/content";
import {migrateDatabase} from "@/lib/db/migrate";
import {getCurriculumGrade,getDetail} from "@/lib/content/public-repository";

const directories:string[]=[];const directory=mkdtempSync(join(tmpdir(),"quan-su-viet-grade-10-"));directories.push(directory);const databasePath=join(directory,"grade-10.db");
type SeedResult={mode:string;asOf:string;review:string;copyright:string;lessons:number;translations:number;lessonTranslations:number;sources:number;claims:number;evidence:number;mappings:number};
function seed(path:string,extraEnv:Record<string,string>={}){return spawnSync(resolve("node_modules/.bin/tsx"),["scripts/seed.ts"],{cwd:resolve("."),encoding:"utf8",env:{...process.env,DATABASE_PATH:path,...extraEnv}});}
function successfulSeed(path:string,extraEnv:Record<string,string>={}){const result=seed(path,extraEnv);if(result.status!==0)throw new Error(result.stderr);return JSON.parse(result.stdout) as SeedResult|Record<string,number>;}
let firstBatch:SeedResult;let secondBatch:SeedResult;
beforeAll(()=>{migrateDatabase(databasePath);expect(successfulSeed(databasePath)).toEqual({contentNodes:50,translations:100,sources:50,users:3,curriculumRequirements:55,curriculumMappings:23});expect(successfulSeed(databasePath,{GRADE_6_SEED_ONLY:"1"})).toMatchObject({lessons:8});expect(successfulSeed(databasePath,{GRADE_7_SEED_ONLY:"1"})).toMatchObject({lessons:6});expect(successfulSeed(databasePath,{GRADE_8_SEED_ONLY:"1"})).toMatchObject({lessons:7});expect(successfulSeed(databasePath,{GRADE_9_SEED_ONLY:"1"})).toMatchObject({lessons:6});firstBatch=successfulSeed(databasePath,{NODE_ENV:"production",GRADE_10_SEED_ONLY:"1",SEED_ADMIN_PASSWORD:"",SEED_EDITOR_PASSWORD:"",SEED_REVIEWER_PASSWORD:""}) as SeedResult;secondBatch=successfulSeed(databasePath,{GRADE_10_SEED_ONLY:"1"}) as SeedResult;},120_000);
afterAll(()=>{for(const path of directories)rmSync(path,{recursive:true,force:true});});

describe("C-032 Grade 10 curriculum batch",()=>{
  it("preserves base and Grades 6–9 while remaining idempotent",()=>{expect(firstBatch).toEqual({mode:"grade-10-only",asOf:grade10BatchAsOf,review:"internal-c032-not-historian-council",copyright:"citations-only-no-third-party-binaries",lessons:10,translations:20,lessonTranslations:20,sources:12,claims:20,evidence:20,mappings:10});expect(secondBatch).toEqual(firstBatch);const db=new Database(databasePath,{readonly:true});try{expect(db.prepare("SELECT COUNT(*) AS count FROM content_nodes").get()).toEqual({count:87});expect(db.prepare("SELECT COUNT(*) AS count FROM content_nodes WHERE id LIKE 'lesson-g6-%'").get()).toEqual({count:grade6Lessons.length});expect(db.prepare("SELECT COUNT(*) AS count FROM content_nodes WHERE id LIKE 'lesson-g7-%'").get()).toEqual({count:grade7Lessons.length});expect(db.prepare("SELECT COUNT(*) AS count FROM content_nodes WHERE id LIKE 'lesson-g8-%'").get()).toEqual({count:grade8Lessons.length});expect(db.prepare("SELECT COUNT(*) AS count FROM content_nodes WHERE id LIKE 'lesson-g9-%'").get()).toEqual({count:grade9Lessons.length});expect(db.prepare("SELECT COUNT(*) AS count FROM content_nodes WHERE id LIKE 'lesson-g10-%'").get()).toEqual({count:10});}finally{db.close();}});

  it("keeps mandatory and elective coverage separate",()=>{const db=new Database(databasePath,{readonly:true});try{for(const locale of ["vi","en"] as const){const mandatory=getCurriculumGrade(db,locale,"10",new URLSearchParams({track:"MANDATORY",pageSize:"50"})).data;expect(mandatory.summary).toEqual({requirementCount:7,publishedRequirementCount:7,verifiedRequirementCount:7,fullCoverage:true});expect(mandatory.requirements).toHaveLength(7);expect(mandatory.requirements.every(({track})=>track==="MANDATORY")).toBe(true);const elective=getCurriculumGrade(db,locale,"10",new URLSearchParams({track:"ELECTIVE",pageSize:"50"})).data;expect(elective.summary).toEqual({requirementCount:3,publishedRequirementCount:3,verifiedRequirementCount:3,fullCoverage:true});expect(elective.requirements).toHaveLength(3);expect(elective.requirements.every(({track})=>track==="ELECTIVE")).toBe(true);for(const lesson of grade10Lessons){const value=lesson[locale];const detail=getDetail(db,locale,"TOPIC",value.slug).data;expect(detail).toMatchObject({id:lesson.id,title:value.title,asOf:grade10BatchAsOf,reviewedBy:expect.stringContaining("C-032"),lesson:{learningObjectives:value.learningObjectives,originalSummary:value.originalSummary,analysis:value.analysis,debates:value.debates}});expect(detail.claims).toHaveLength(2);expect(detail.claims.every(({evidence})=>evidence.length===1&&evidence[0].locator.length>0&&evidence[0].quote===null)).toBe(true);expect(detail.sources.every(({verificationStatus})=>verificationStatus==="VERIFIED")).toBe(true);expect(detail.media).toEqual([]);}}}finally{db.close();}});

  it("keeps original bilingual prose and citation-only source governance",()=>{const db=new Database(databasePath,{readonly:true});try{expect(db.prepare("SELECT COUNT(*) AS count FROM content_media WHERE content_id LIKE 'lesson-g10-%'").get()).toEqual({count:0});expect(db.prepare("SELECT COUNT(*) AS count FROM sources WHERE id LIKE 'source-g10-%' AND url LIKE 'https://%' AND citation_note LIKE '%không tải hoặc sao chép tệp nhị phân%'").get()).toEqual({count:12});expect(db.prepare("SELECT verification_status,COUNT(*) AS count FROM content_claims WHERE id LIKE 'claim-g10-%' GROUP BY verification_status").all()).toEqual([{verification_status:"VERIFIED",count:20}]);}finally{db.close();}for(const lesson of grade10Lessons){expect(lesson.vi.body.length).toBeGreaterThan(1000);expect(lesson.en.body.length).toBeGreaterThan(1000);expect(lesson.vi.body).not.toBe(lesson.en.body);expect(lesson.vi.analysis.length).toBeGreaterThan(250);expect(lesson.en.analysis.length).toBeGreaterThan(250);}expect(new Set(grade10Sources.map(({url})=>url)).size).toBe(12);});

  it("covers all mandatory and elective outcomes without period laundering",()=>{const byId=new Map(grade10Lessons.map((lesson)=>[lesson.requirementId,`${lesson.vi.body}\n${lesson.en.body}`.toLocaleLowerCase("vi")]));const required:Record<string,string[]>={"g10-history-and-historiography":["hiện thực lịch sử","tư liệu","phương pháp","evidence"],"g10-roles-of-history":["di sản","tương lai","unesco","heritage"],"g10-ancient-medieval-world-civilisations":["lưỡng hà","ai cập","ấn độ","trung hoa","hy lạp","la mã","mesopotamia","egypt"],"g10-industrial-revolutions-world-history":["hơi nước","điện","máy tính","ai","steam","electricity","internet"],"g10-southeast-asian-civilisation":["đông nam á","chăm-pa","mỹ sơn","thương mại","southeast asia","champa","my son"],"g10-civilisations-on-vietnamese-territory":["đông sơn","chăm-pa","óc eo","phù nam","đại việt","thăng long","đông sơn","champa","thăng long"],"g10-vietnamese-ethnic-communities":["54","tộc người","đoàn kết","ethnic group","solidarity"],"g10-fields-of-historical-study":["khảo cổ","xã hội","kinh tế","môi trường","digital","archaeology"],"g10-heritage-conservation":["hoi an","huế","bảo tồn","residents","hue","conservation"],"g10-state-and-law-vietnam":["hiến pháp","1946","1959","1980","1992","2013","constitution"]};expect([...byId.keys()]).toEqual(Object.keys(required));for(const [id,markers] of Object.entries(required))for(const marker of markers)expect(byId.get(id),`${id} must cover ${marker}`).toContain(marker);});

  it("refuses manual edits unless explicitly overridden and rejects mixed modes",()=>{const protectedDirectory=mkdtempSync(join(tmpdir(),"quan-su-viet-grade-10-protection-"));directories.push(protectedDirectory);const path=join(protectedDirectory,"protected.db");migrateDatabase(path);successfulSeed(path);successfulSeed(path,{GRADE_10_SEED_ONLY:"1"});const db=new Database(path);db.prepare("UPDATE sources SET title=?,updated_at=? WHERE id=?").run("Biên tập thủ công cần giữ nguyên","2026-08-13T12:00:00.000Z","source-g10-ubdt-54");db.close();const rejected=seed(path,{GRADE_10_SEED_ONLY:"1"});expect(rejected.status).not.toBe(0);expect(rejected.stderr).toContain("Refusing to replace edited Grade 10 row sources.source-g10-ubdt-54");expect(successfulSeed(path,{GRADE_10_SEED_ONLY:"1",ALLOW_GRADE_10_BATCH_UPDATE:"1"})).toEqual(firstBatch);const mixed=seed(path,{GRADE_10_SEED_ONLY:"1",GRADE_9_SEED_ONLY:"1"});expect(mixed.status).not.toBe(0);expect(mixed.stderr).toContain("GRADE_9_SEED_ONLY, and GRADE_10_SEED_ONLY cannot be combined");},40_000);
});
