import Database from "better-sqlite3";
import {spawnSync} from "node:child_process";
import {mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join,resolve} from "node:path";
import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {grade6Lessons} from "@/data/curriculum/grade-6/content";
import {grade7Lessons} from "@/data/curriculum/grade-7/content";
import {grade8Lessons} from "@/data/curriculum/grade-8/content";
import {grade9Lessons} from "@/data/curriculum/grade-9/content";
import {grade10Lessons} from "@/data/curriculum/grade-10/content";
import {grade11BatchAsOf,grade11Lessons,grade11Sources} from "@/data/curriculum/grade-11/content";
import {migrateDatabase} from "@/lib/db/migrate";
import {getCurriculumGrade,getDetail} from "@/lib/content/public-repository";

const directories:string[]=[];const directory=mkdtempSync(join(tmpdir(),"quan-su-viet-grade-11-"));directories.push(directory);const databasePath=join(directory,"grade-11.db");
type SeedResult={mode:string;asOf:string;review:string;copyright:string;lessons:number;translations:number;lessonTranslations:number;sources:number;claims:number;evidence:number;mappings:number};
function seed(path:string,extraEnv:Record<string,string>={}){return spawnSync(resolve("node_modules/.bin/tsx"),["scripts/seed.ts"],{cwd:resolve("."),encoding:"utf8",env:{...process.env,DATABASE_PATH:path,...extraEnv}});}
function successfulSeed(path:string,extraEnv:Record<string,string>={}){const result=seed(path,extraEnv);if(result.status!==0)throw new Error(result.stderr);return JSON.parse(result.stdout) as SeedResult|Record<string,number>;}
let firstBatch:SeedResult;let secondBatch:SeedResult;
beforeAll(()=>{migrateDatabase(databasePath);expect(successfulSeed(databasePath)).toEqual({contentNodes:50,translations:100,sources:50,users:3,curriculumRequirements:55,curriculumMappings:23});expect(successfulSeed(databasePath,{GRADE_6_SEED_ONLY:"1"})).toMatchObject({lessons:8});expect(successfulSeed(databasePath,{GRADE_7_SEED_ONLY:"1"})).toMatchObject({lessons:6});expect(successfulSeed(databasePath,{GRADE_8_SEED_ONLY:"1"})).toMatchObject({lessons:7});expect(successfulSeed(databasePath,{GRADE_9_SEED_ONLY:"1"})).toMatchObject({lessons:6});expect(successfulSeed(databasePath,{GRADE_10_SEED_ONLY:"1"})).toMatchObject({lessons:10});firstBatch=successfulSeed(databasePath,{NODE_ENV:"production",GRADE_11_SEED_ONLY:"1",SEED_ADMIN_PASSWORD:"",SEED_EDITOR_PASSWORD:"",SEED_REVIEWER_PASSWORD:""}) as SeedResult;secondBatch=successfulSeed(databasePath,{GRADE_11_SEED_ONLY:"1"}) as SeedResult;},120_000);
afterAll(()=>{for(const path of directories)rmSync(path,{recursive:true,force:true});});

describe("C-033 Grade 11 curriculum batch",()=>{
  it("preserves earlier batches and remains idempotent",()=>{expect(firstBatch).toEqual({mode:"grade-11-only",asOf:grade11BatchAsOf,review:"internal-c033-not-historian-council",copyright:"citations-only-no-third-party-binaries",lessons:9,translations:18,lessonTranslations:18,sources:13,claims:18,evidence:18,mappings:9});expect(secondBatch).toEqual(firstBatch);const db=new Database(databasePath,{readonly:true});try{expect(db.prepare("SELECT COUNT(*) AS count FROM content_nodes").get()).toEqual({count:96});for(const [prefix,count] of [["g6",grade6Lessons.length],["g7",grade7Lessons.length],["g8",grade8Lessons.length],["g9",grade9Lessons.length],["g10",grade10Lessons.length],["g11",9] ] as const)expect(db.prepare("SELECT COUNT(*) AS count FROM content_nodes WHERE id LIKE ?").get(`lesson-${prefix}-%`)).toEqual({count});}finally{db.close();}});
  it("keeps mandatory and elective tracks separate in VI and EN",()=>{const db=new Database(databasePath,{readonly:true});try{for(const locale of ["vi","en"] as const){const mandatory=getCurriculumGrade(db,locale,"11",new URLSearchParams({track:"MANDATORY",pageSize:"50"})).data;expect(mandatory.summary).toEqual({requirementCount:6,publishedRequirementCount:6,verifiedRequirementCount:6,fullCoverage:true});expect(mandatory.requirements).toHaveLength(6);expect(mandatory.requirements.every(({track})=>track==="MANDATORY")).toBe(true);const elective=getCurriculumGrade(db,locale,"11",new URLSearchParams({track:"ELECTIVE",pageSize:"50"})).data;expect(elective.summary).toEqual({requirementCount:3,publishedRequirementCount:3,verifiedRequirementCount:3,fullCoverage:true});expect(elective.requirements).toHaveLength(3);expect(elective.requirements.every(({track})=>track==="ELECTIVE")).toBe(true);}}finally{db.close();}});
  it("requires source locators, sensitive review disclosure, bilingual prose, and no media",()=>{const db=new Database(databasePath,{readonly:true});try{for(const lesson of grade11Lessons){for(const locale of ["vi","en"] as const){const detail=getDetail(db,locale,"TOPIC",lesson[locale].slug).data;expect(detail).toMatchObject({id:lesson.id,asOf:grade11BatchAsOf,reviewedBy:expect.stringContaining("C-033")});expect(detail.claims).toHaveLength(2);expect(detail.claims.every(({evidence})=>evidence.length===1&&evidence[0].locator.length>0&&evidence[0].quote===null)).toBe(true);expect(detail.sources.every(({verificationStatus})=>verificationStatus==="VERIFIED")).toBe(true);expect(detail.media).toEqual([]);}}expect(db.prepare("SELECT COUNT(*) AS count FROM content_media WHERE content_id LIKE 'lesson-g11-%'").get()).toEqual({count:0});expect(db.prepare("SELECT COUNT(*) AS count FROM sources WHERE id LIKE 'source-g11-%' AND citation_note LIKE '%không tải hoặc sao chép tệp nhị phân%'").get()).toEqual({count:13});}finally{db.close();}for(const lesson of grade11Lessons){expect(lesson.vi.body.length).toBeGreaterThan(1400);expect(lesson.en.body.length).toBeGreaterThan(1400);expect(lesson.vi.body).not.toBe(lesson.en.body);expect(lesson.vi.analysis.length).toBeGreaterThan(250);expect(lesson.en.analysis.length).toBeGreaterThan(250);}expect(new Set(grade11Sources.map(({url})=>url)).size).toBe(12);});
  it("covers period, sovereignty, reform, defence, and elective outcomes",()=>{const byId=new Map(grade11Lessons.map(lesson=>[lesson.requirementId,`${lesson.vi.body}\n${lesson.en.body}`.toLocaleLowerCase("vi")]));const required:Record<string,string[]>={"g11-bourgeois-revolutions-capitalism":["cách mạng tư sản","chủ nghĩa tư bản","bourgeois","capitalism"],"g11-socialism-since-1917":["1917","chủ nghĩa xã hội","socialism","1991"],"g11-southeast-asian-independence":["đông nam á","độc lập","asean","independence"],"g11-vietnam-national-defence-before-1945":["bạch đằng","938","981","1288","defence","liberation"],"g11-major-vietnamese-reforms":["hồ quý ly","cải cách","1858","reform"],"g11-east-sea-sovereignty":["hoàng sa","trường sa","unclos","chủ quyền","sovereignty","peaceful"],"g11-traditional-vietnamese-arts":["nghệ thuật truyền thống","di sản","traditional vietnamese arts","community"],"g11-war-and-peace-twentieth-century":["chiến tranh","hòa bình","liên hợp quốc","war","peace","united nations"],"g11-notable-vietnamese-figures":["danh nhân","nguồn","notable figure","evidence"]};expect([...byId.keys()]).toEqual(Object.keys(required));for(const [id,markers] of Object.entries(required))for(const marker of markers)expect(byId.get(id),`${id} must cover ${marker}`).toContain(marker);});
  it("refuses manual edits and mixed seed modes",()=>{const protectedDirectory=mkdtempSync(join(tmpdir(),"quan-su-viet-grade-11-protection-"));directories.push(protectedDirectory);const path=join(protectedDirectory,"protected.db");migrateDatabase(path);successfulSeed(path);successfulSeed(path,{GRADE_11_SEED_ONLY:"1"});const db=new Database(path);db.prepare("UPDATE sources SET title=?,updated_at=? WHERE id=?").run("Biên tập thủ công cần giữ nguyên","2026-08-13T12:00:00.000Z","source-g11-unclos");db.close();const rejected=seed(path,{GRADE_11_SEED_ONLY:"1"});expect(rejected.status).not.toBe(0);expect(rejected.stderr).toContain("Refusing to replace edited Grade 11 row sources.source-g11-unclos");expect(successfulSeed(path,{GRADE_11_SEED_ONLY:"1",ALLOW_GRADE_11_BATCH_UPDATE:"1"})).toEqual(firstBatch);const mixed=seed(path,{GRADE_10_SEED_ONLY:"1",GRADE_11_SEED_ONLY:"1"});expect(mixed.status).not.toBe(0);expect(mixed.stderr).toContain("GRADE_10_SEED_ONLY, and GRADE_11_SEED_ONLY cannot be combined");},40_000);
});
