import { resolve } from "node:path";
import { mkdir,writeFile } from "node:fs/promises";
import { expect,test,type Page } from "@playwright/test";

const axePath=resolve("node_modules/axe-core/axe.min.js");
async function blockingAxe(page:Page){await page.addScriptTag({path:axePath});return page.evaluate(async()=>{const axe=(window as unknown as {axe:{run:(root:Document,options:unknown)=>Promise<{violations:Array<{id:string;impact:string|null}>}>}}).axe;const result=await axe.run(document,{runOnly:{type:"tag",values:["wcag2a","wcag2aa","wcag21aa"]}});return result.violations.filter(({impact})=>impact==="critical"||impact==="serious");});}
async function trackLcp(page:Page){await page.addInitScript(()=>{(globalThis as typeof globalThis&{__brandLcp?:number}).__brandLcp=0;new PerformanceObserver((list)=>{for(const entry of list.getEntries())(globalThis as typeof globalThis&{__brandLcp?:number}).__brandLcp=Math.max((globalThis as typeof globalThis&{__brandLcp?:number}).__brandLcp??0,entry.startTime);}).observe({type:"largest-contentful-paint",buffered:true});});}
async function metrics(page:Page){return page.evaluate(()=>({clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,lcpMs:(globalThis as typeof globalThis&{__brandLcp?:number}).__brandLcp??0}));}

test("one SVG brand mark identifies public, editorial, docs, and favicon surfaces",async({browser,baseURL})=>{
  test.setTimeout(120_000);if(!baseURL)throw new Error("baseURL is required");await mkdir("artifacts/brand-system",{recursive:true});
  const desktopContext=await browser.newContext({viewport:{width:1440,height:1000}});const desktop=await desktopContext.newPage();await trackLcp(desktop);await desktop.goto(`${baseURL}/vi/su-kien`,{waitUntil:"networkidle"});const desktopMark=desktop.locator(".site-header svg.brand-mark");await expect(desktopMark).toBeVisible();await expect(desktopMark.locator('circle[cx="24"][cy="24"][r="21"]')).toHaveCount(1);await desktop.waitForTimeout(400);const desktopAxe=await blockingAxe(desktop);expect(desktopAxe).toEqual([]);const desktopMetrics=await metrics(desktop);expect(desktopMetrics.scrollWidth).toBe(desktopMetrics.clientWidth);expect(desktopMetrics.lcpMs).toBeLessThanOrEqual(2500);await desktop.locator(".site-header").screenshot({path:"artifacts/brand-system/brand-system-desktop.png"});await desktop.getByRole("link",{name:"Quân Sử Việt, trang chủ"}).click();await expect(desktop).toHaveURL(`${baseURL}/vi`);await desktop.goto(`${baseURL}/docs`,{waitUntil:"domcontentloaded"});await expect(desktop.locator("header svg.brand-mark")).toBeVisible();await desktopContext.close();

  const mobileContext=await browser.newContext({viewport:{width:390,height:844}});const mobile=await mobileContext.newPage();await trackLcp(mobile);await mobile.goto(`${baseURL}/en/events`,{waitUntil:"networkidle"});const englishBrand=mobile.getByRole("link",{name:"Quân Sử Việt, home"});await englishBrand.focus();await mobile.keyboard.press("Enter");await expect(mobile).toHaveURL(`${baseURL}/en`);await mobile.goto(`${baseURL}/admin/login`,{waitUntil:"networkidle"});const loginMark=mobile.locator(".login-brand svg.brand-mark");await expect(loginMark).toBeVisible();await expect(loginMark).toHaveCSS("width","38px");await mobile.waitForTimeout(400);const mobileAxe=await blockingAxe(mobile);expect(mobileAxe).toEqual([]);const mobileMetrics=await metrics(mobile);expect(mobileMetrics.scrollWidth).toBe(mobileMetrics.clientWidth);expect(mobileMetrics.lcpMs).toBeLessThanOrEqual(2500);await mobile.locator(".login-card").screenshot({path:"artifacts/brand-system/brand-system-mobile.png"});await mobileContext.close();

  const favicon=await fetch(`${baseURL}/icon.svg`);expect(favicon.ok).toBe(true);expect(favicon.headers.get("content-type")).toContain("image/svg+xml");const faviconSvg=await favicon.text();expect(faviconSvg).toContain('cx="24" cy="24" r="21"');expect(faviconSvg).toContain("M10 31c4.7-3.8");
  const proof={generatedAt:new Date().toISOString(),url:new URL(baseURL).origin,surfaces:{publicHeader:true,publicFooter:true,adminLogin:true,adminSidebarStatic:true,docs:true},geometry:{viewBox:"0 0 48 48",outerCircle:"24,24,21",sun:true,historyFlow:true,strokeWidth:1.8,currentColor:true},navigation:{pointer:"/vi",keyboard:"/en"},favicon:{path:"/icon.svg",status:favicon.status,contentType:favicon.headers.get("content-type")},accessibility:{desktopCriticalOrSerious:desktopAxe.length,mobileCriticalOrSerious:mobileAxe.length},desktopMetrics,mobileMetrics,screenshots:["artifacts/brand-system/brand-system-desktop.png","artifacts/brand-system/brand-system-mobile.png"]};await writeFile("artifacts/brand-system/brand-system-proof.json",`${JSON.stringify(proof,null,2)}\n`);
});
