import { expect,test } from "@playwright/test";
import { login,releaseOrigin } from "./support";

test("editorial claim and source verification gates publish",async({browser})=>{
  const suffix=`claim-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;
  const viSlug=`${suffix}-vi`;const enSlug=`${suffix}-en`;
  const editorContext=await browser.newContext({baseURL:releaseOrigin()});const editor=await editorContext.newPage();await login(editor,"EDITOR");
  await editor.goto("/admin/contents/new");await editor.getByLabel("Tiêu đề",{exact:true}).fill(`Claim proof ${suffix}`);await editor.getByLabel("Slug",{exact:true}).fill(viSlug);await editor.getByLabel("Tóm tắt",{exact:true}).fill("Nội dung kiểm tra claim có nguồn.");await editor.getByLabel("Nội dung",{exact:true}).fill("Bài kiểm tra quy trình claim và evidence.");await editor.getByRole("button",{name:"Tạo bản nháp",exact:true}).click();await editor.waitForURL(/\/admin\/contents\/(?!new(?:$|[/?]))[^/]+$/);const contentUrl=editor.url();
  await editor.getByRole("tab",{name:"English",exact:true}).click();await editor.getByLabel("Title",{exact:true}).fill(`Claim proof ${suffix}`);await editor.getByLabel("Slug",{exact:true}).fill(enSlug);await editor.getByLabel("Summary",{exact:true}).fill("Claim evidence workflow proof.");await editor.getByLabel("Body",{exact:true}).fill("A source-backed claim workflow proof.");await editor.getByRole("button",{name:"Lưu bản EN",exact:true}).click();
  const sourceColumn=editor.locator(".attachment-columns > div").first();await sourceColumn.getByText("+ Thêm nguồn",{exact:true}).click();const sourceForm=sourceColumn.locator(".mini-form");await sourceForm.getByLabel("Tiêu đề",{exact:true}).fill(`Institutional source ${suffix}`);await sourceForm.getByLabel("Nhà xuất bản",{exact:true}).fill("Encyclopaedia Britannica");await sourceForm.locator('select[name="sourceType"]').selectOption("REFERENCE_WORK");await sourceForm.locator('select[name="qualityTier"]').selectOption("TIER_4_CONTEXTUAL");await sourceForm.getByLabel("URL HTTPS",{exact:true}).fill(`https://example.com/${suffix}`);await sourceForm.getByLabel("Ngày truy cập",{exact:true}).fill("2026-08-13T12:00");await sourceForm.getByRole("button",{name:"Tạo và gắn nguồn",exact:true}).click();await expect(editor.getByText("Đã tạo và gắn nguồn.",{exact:false})).toBeVisible();
  const claim=editor.locator(".claims-card");await claim.getByLabel("Luận điểm VI",{exact:true}).fill("Nguồn thể chế được gắn với claim thông qua locator cụ thể.");await claim.getByLabel("Claim EN",{exact:true}).fill("An institutional source is attached to this claim through a specific locator.");await claim.locator("select").nth(2).selectOption({index:1});await claim.getByLabel("Locator",{exact:true}).fill("section 1, workflow proof");await claim.getByRole("button",{name:"Tạo luận điểm",exact:true}).click();await expect(editor.getByText("Đã tạo luận điểm và gắn bằng chứng.",{exact:false})).toBeVisible();await claim.getByRole("button",{name:"Gửi kiểm chứng",exact:true}).click();await expect(editor.getByText("Đã gửi luận điểm tới danh sách kiểm chứng.",{exact:false})).toBeVisible();await editor.getByRole("button",{name:"Gửi duyệt",exact:true}).click();await expect(editor.getByText("Đã gửi nội dung tới danh sách chờ duyệt.",{exact:false})).toBeVisible();
  const reviewerContext=await browser.newContext({baseURL:releaseOrigin()});const reviewer=await reviewerContext.newPage();await login(reviewer,"REVIEWER");await reviewer.goto("/admin/sources");const sourceRow=reviewer.getByRole("row").filter({hasText:`Institutional source ${suffix}`});await sourceRow.getByRole("button",{name:"Gửi kiểm chứng",exact:true}).click();await sourceRow.getByRole("button",{name:"Xác minh",exact:true}).click();await expect(sourceRow).toContainText("VERIFIED");
  await reviewer.goto(new URL(contentUrl).pathname);const reviewerClaims=reviewer.locator(".claims-card");await reviewerClaims.getByRole("button",{name:"Xác minh claim",exact:true}).click();await expect(reviewerClaims).toContainText("VERIFIED");
  await reviewer.getByRole("button",{name:"Duyệt nội dung",exact:true}).click();await expect(reviewer.getByText("Đã duyệt nội dung.",{exact:false})).toBeVisible();await reviewer.getByRole("button",{name:"Xuất bản",exact:true}).click();await expect(reviewer.getByText("Đã xuất bản nội dung.",{exact:false})).toBeVisible();const publicHref=await reviewer.getByRole("link",{name:"Mở trang công khai",exact:true}).getAttribute("href");expect(publicHref).toBe(`/vi/su-kien/${viSlug}`);const publicPage=await reviewerContext.newPage();await publicPage.goto(publicHref!);await expect(publicPage.getByRole("heading",{name:`Claim proof ${suffix}`,exact:true})).toBeVisible();
  await editorContext.close();await reviewerContext.close();
});
