import { mkdir,writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { expect,test,type Locator,type Page } from "@playwright/test";

type RuntimeImage={id:string;src:string;alt:string;complete:boolean;naturalWidth:number;naturalHeight:number;renderedWidth:number;renderedHeight:number};
const axePath=resolve("node_modules/axe-core/axe.min.js");

async function imageRuntime(locator:Locator):Promise<RuntimeImage>{return locator.evaluate((element)=>{const image=element as HTMLImageElement;return{id:image.dataset.featuredArt??image.dataset.detailArt??"",src:new URL(image.currentSrc||image.src).pathname,alt:image.alt,complete:image.complete,naturalWidth:image.naturalWidth,naturalHeight:image.naturalHeight,renderedWidth:image.getBoundingClientRect().width,renderedHeight:image.getBoundingClientRect().height};});}
async function addMetrics(page:Page){await page.addInitScript(()=>{const state=globalThis as typeof globalThis&{__featuredCls?:number;__featuredLcp?:number};state.__featuredCls=0;state.__featuredLcp=0;new PerformanceObserver((list)=>{for(const entry of list.getEntries()){const shift=entry as PerformanceEntry&{hadRecentInput?:boolean;value?:number};if(!shift.hadRecentInput)state.__featuredCls=(state.__featuredCls??0)+(shift.value??0);}}).observe({type:"layout-shift",buffered:true});new PerformanceObserver((list)=>{for(const entry of list.getEntries())state.__featuredLcp=Math.max(state.__featuredLcp??0,entry.startTime);}).observe({type:"largest-contentful-paint",buffered:true});});}
async function blockingAxe(page:Page){await page.addScriptTag({path:axePath});return page.evaluate(async()=>{const axe=(window as unknown as {axe:{run:(root:Document,options:unknown)=>Promise<{violations:Array<{id:string;impact:string|null}>}>}}).axe;const result=await axe.run(document,{runOnly:{type:"tag",values:["wcag2a","wcag2aa","wcag21aa"]}});return result.violations.filter(({impact})=>impact==="critical"||impact==="serious");});}
async function openByKeyboard(page:Page,id:string){const image=page.locator(`img[data-featured-art="${id}"]`);await image.scrollIntoViewIfNeeded();const article=image.locator("xpath=ancestor::article");const link=article.locator("h3 a");const href=await link.getAttribute("href");if(!href)throw new Error(`Missing detail href for ${id}`);const src=(await imageRuntime(image)).src;await link.focus();await expect(link).toBeFocused();await link.press("Enter");await expect(page).toHaveURL(new RegExp(`${href.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}$`));const detail=page.locator(`img[data-detail-art="${id}"]`);await expect(detail).toBeVisible();await expect.poll(async()=>(await imageRuntime(detail)).naturalWidth).toBeGreaterThan(0);const runtime=await imageRuntime(detail);expect(runtime.src).toBe(src);expect(runtime.alt.length).toBeGreaterThan(20);return{href,cardSrc:src,detail:runtime};}

test("featured illustrations stay consistent from bilingual cards to event and artifact details",async({browser,baseURL})=>{
  test.setTimeout(120_000);if(!baseURL)throw new Error("baseURL is required");await mkdir("artifacts/featured-images",{recursive:true});
  const desktopContext=await browser.newContext({viewport:{width:1440,height:1000}});const desktop=await desktopContext.newPage();await addMetrics(desktop);await desktop.goto(`${baseURL}/vi`,{waitUntil:"networkidle"});
  const images=desktop.locator("img[data-featured-art]");await expect(images).toHaveCount(6);for(let index=0;index<6;index+=1){const image=images.nth(index);await image.scrollIntoViewIfNeeded();await expect.poll(async()=>(await imageRuntime(image)).naturalWidth).toBeGreaterThan(0);}
  const desktopRuntime=await images.evaluateAll((elements)=>elements.map((element)=>{const image=element as HTMLImageElement;return{id:image.dataset.featuredArt??"",src:new URL(image.currentSrc||image.src).pathname,alt:image.alt,complete:image.complete,naturalWidth:image.naturalWidth,naturalHeight:image.naturalHeight,renderedWidth:image.getBoundingClientRect().width,renderedHeight:image.getBoundingClientRect().height};}));
  expect(new Set(desktopRuntime.map(({id})=>id)).size).toBe(6);expect(new Set(desktopRuntime.map(({src})=>src)).size).toBe(6);for(const image of desktopRuntime){expect(image.complete).toBe(true);expect(image.alt).toBe("");expect(image.naturalWidth).toBe(1280);expect(image.naturalHeight).toBe(853);expect(image.renderedWidth/image.renderedHeight).toBeCloseTo(1.6,1);}
  await desktop.screenshot({path:"artifacts/featured-images/desktop.png",fullPage:true});const homeMetrics=await desktop.evaluate(()=>{const state=globalThis as typeof globalThis&{__featuredCls?:number;__featuredLcp?:number};return{cumulativeLayoutShift:state.__featuredCls??0,lcpMs:state.__featuredLcp??0,clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth};});expect(homeMetrics.cumulativeLayoutShift).toBeLessThanOrEqual(.1);expect(homeMetrics.lcpMs).toBeLessThanOrEqual(2500);expect(homeMetrics.scrollWidth).toBe(homeMetrics.clientWidth);expect(await blockingAxe(desktop)).toEqual([]);
  const event=await openByKeyboard(desktop,"event-dien-bien-phu");await expect(desktop.getByText("Minh họa nguyên bản, không phải ảnh tư liệu lịch sử hay bản sao hiện vật.",{exact:true})).toBeVisible();await desktop.locator(".detail-art").screenshot({path:"artifacts/featured-images/detail.png"});expect(await blockingAxe(desktop)).toEqual([]);await desktop.goBack({waitUntil:"networkidle"});
  const artifact=await openByKeyboard(desktop,"artifact-bach-dang-stakes");await expect(desktop.getByText("Minh họa nguyên bản, không phải ảnh tư liệu lịch sử hay bản sao hiện vật.",{exact:true})).toBeVisible();expect(await blockingAxe(desktop)).toEqual([]);
  const transfers=[];for(const {src} of desktopRuntime){const response=await desktop.request.get(`${baseURL}${src}`);expect(response.ok()).toBe(true);transfers.push({src,bytes:(await response.body()).byteLength,contentType:response.headers()["content-type"]});}const totalTransferBytes=transfers.reduce((sum,item)=>sum+item.bytes,0);expect(totalTransferBytes).toBeLessThanOrEqual(1_800_000);for(const item of transfers)expect(item.contentType).toContain("image/webp");await desktopContext.close();

  const mobileContext=await browser.newContext({viewport:{width:390,height:844}});const mobile=await mobileContext.newPage();await mobile.goto(`${baseURL}/en`,{waitUntil:"networkidle"});const mobileImages=mobile.locator("img[data-featured-art]");await expect(mobileImages).toHaveCount(6);for(let index=0;index<6;index+=1){const image=mobileImages.nth(index);await image.scrollIntoViewIfNeeded();await expect.poll(async()=>(await imageRuntime(image)).naturalWidth).toBeGreaterThan(0);}const mobileViewport=await mobile.evaluate(()=>({clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth}));expect(mobileViewport.scrollWidth).toBe(mobileViewport.clientWidth);await mobile.screenshot({path:"artifacts/featured-images/mobile.png",fullPage:true});const english=await openByKeyboard(mobile,"event-bach-dang-938");await expect(mobile.getByText("Original illustration, not a historical photograph or artifact reproduction.",{exact:true})).toBeVisible();expect(english.detail.alt).toMatch(/^Illustration /);expect(await blockingAxe(mobile)).toEqual([]);await mobileContext.close();

  const proof={generatedAt:new Date().toISOString(),url:new URL(baseURL).origin,images:desktopRuntime,transfers,totalTransferBytes,homeMetrics,mobileViewport,journeys:{event,artifact,english},accessibility:{criticalOrSerious:0},screenshots:["artifacts/featured-images/desktop.png","artifacts/featured-images/mobile.png","artifacts/featured-images/detail.png"]};await writeFile("artifacts/featured-images/featured-images-proof.json",`${JSON.stringify(proof,null,2)}\n`);
});
