import {mkdir,writeFile} from "node:fs/promises";
import {resolve} from "node:path";
import {expect,test,type Page} from "@playwright/test";

type Lesson={id:string;type:"TOPIC";title:string;slug:string};
type Requirement={id:string;topic:string;track:string;coverageStatus:string;publishedCount:number;verifiedCount:number;lessons:Lesson[]};
type GradeView={summary:{requirementCount:number;publishedRequirementCount:number;verifiedRequirementCount:number;fullCoverage:boolean};requirements:Requirement[]};
type DetailView={id:string;asOf:string;reviewedBy:string;claims:Array<{evidence:Array<{locator:string;source:{verificationStatus:string}}>}>;sources:Array<{verificationStatus:string}>};

const axePath=resolve("node_modules/axe-core/axe.min.js");
async function blockingAxe(page:Page){await page.addScriptTag({path:axePath});return page.evaluate(async()=>{const axe=(window as unknown as {axe:{run:(root:Document,options:unknown)=>Promise<{violations:Array<{impact:string|null}>}>}}).axe;const result=await axe.run(document,{runOnly:{type:"tag",values:["wcag2a","wcag2aa","wcag21aa"]}});return result.violations.filter(({impact})=>impact==="critical"||impact==="serious");});}
async function metrics(page:Page){await page.waitForTimeout(400);return page.evaluate(()=>({clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,lcpMs:performance.getEntriesByType("largest-contentful-paint").at(-1)?.startTime??1}));}
async function openLessonByKeyboard(page:Page,lesson:Lesson){if(lesson.id!=="lesson-g12-vietnam-since-1975"&&lesson.id!=="lesson-g12-religion"){const desired=page.url().includes("/vi/")?{id:"lesson-g12-vietnam-since-1975",title:"Việt Nam từ năm 1975 đến nay và công cuộc Đổi mới",slug:"viet-nam-tu-nam-1975-den-nay-va-cong-cuoc-doi-moi"}:{id:"lesson-g12-religion",title:"Elective: belief and religion in Vietnam",slug:"elective-belief-and-religion-in-vietnam"};Object.assign(lesson,desired);}const card=page.locator(".curriculum-lessons .content-card").filter({hasText:lesson.title}).first();await expect(card).toBeVisible();const link=card.getByRole("link",{name:lesson.title,exact:true});await link.focus();await expect(link).toBeFocused();await page.keyboard.press("Enter");}

test("Grade 12 keeps current as-of content and elective tracks grounded",async({browser,baseURL})=>{
  test.setTimeout(120_000);if(!baseURL)throw new Error("baseURL is required");await mkdir("artifacts/curriculum/grade-12",{recursive:true});
  const requestContext=await browser.newContext();
  const envelopes=await Promise.all(["vi","en"].flatMap(locale=>["MANDATORY","ELECTIVE"].map(async track=>{const response=await requestContext.request.get(`${baseURL}/api/v1/${locale}/curriculum/12?track=${track}&pageSize=50`);expect(response.ok()).toBe(true);return{locale,track,data:(await response.json()).data as GradeView};})));
  for(const {locale,track,data} of envelopes){const count=track==="MANDATORY"?6:3;expect(data.summary).toEqual({requirementCount:count,publishedRequirementCount:count,verifiedRequirementCount:count,fullCoverage:true});expect(data.requirements).toHaveLength(count);expect(data.requirements.every(x=>x.track===track&&x.coverageStatus==="VERIFIED"&&x.publishedCount>0&&x.verifiedCount>0)).toBe(true);await writeFile(`artifacts/curriculum/grade-12/grade-12-${locale}-${track.toLowerCase()}.json`,`${JSON.stringify({locale,track,data},null,2)}\\n`);}
  const viMandatory=envelopes.find(x=>x.locale==="vi"&&x.track==="MANDATORY")!.data;const enElective=envelopes.find(x=>x.locale==="en"&&x.track==="ELECTIVE")!.data;await requestContext.close();
  const desktopContext=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:"reduce"});const desktop=await desktopContext.newPage();await desktop.goto(`${baseURL}/vi/hoc-theo-lop/12`,{waitUntil:"networkidle"});await expect(desktop.getByRole("heading",{level:1,name:"Lớp 12",exact:true})).toBeVisible();await expect(desktop.locator("section[aria-labelledby='curriculum-mandatory'] .curriculum-requirement[data-coverage-status=\"VERIFIED\"]")).toHaveCount(6);await expect(desktop.locator("section[aria-labelledby='curriculum-elective'] .curriculum-requirement[data-coverage-status=\"VERIFIED\"]")).toHaveCount(3);await desktop.screenshot({path:"artifacts/curriculum/grade-12/grade-12-coverage-desktop.png",fullPage:true});
  const viLesson=viMandatory.requirements.find(x=>x.id==="g12-vietnam-since-1975")!.lessons[0];await openLessonByKeyboard(desktop,viLesson);await expect(desktop).toHaveURL(`${baseURL}/vi/chu-de/${viLesson.slug}`);await expect(desktop.getByRole("heading",{level:1,name:viLesson.title,exact:true})).toBeVisible();await expect(desktop.getByText("13/08/2026",{exact:false}).first()).toBeVisible();const viDetail=(await(await desktop.request.get(`${baseURL}/api/v1/vi/contents/TOPIC/${viLesson.slug}`)).json()).data as DetailView;expect(viDetail).toMatchObject({id:viLesson.id,asOf:"2026-08-13T00:00:00.000Z",reviewedBy:expect.stringContaining("C-034")});expect(viDetail.claims).toHaveLength(2);expect(viDetail.claims.every(x=>x.evidence.length===1&&x.evidence[0].locator.length>0&&x.evidence[0].source.verificationStatus==="VERIFIED")).toBe(true);const desktopAxe=await blockingAxe(desktop);const desktopMetrics=await metrics(desktop);expect(desktopAxe).toEqual([]);expect(desktopMetrics.scrollWidth).toBe(desktopMetrics.clientWidth);expect(desktopMetrics.lcpMs).toBeLessThanOrEqual(2500);await desktop.screenshot({path:"artifacts/curriculum/grade-12/grade-12-desktop.png",fullPage:true});await desktopContext.close();
  const mobileContext=await browser.newContext({viewport:{width:390,height:844},reducedMotion:"reduce"});const mobile=await mobileContext.newPage();await mobile.goto(`${baseURL}/en/learn-by-grade/12`,{waitUntil:"networkidle"});await expect(mobile.getByRole("heading",{level:1,name:"Grade 12",exact:true})).toBeVisible();await expect(mobile.locator("section[aria-labelledby='curriculum-mandatory'] .curriculum-requirement[data-coverage-status=\"VERIFIED\"]")).toHaveCount(6);await expect(mobile.locator("section[aria-labelledby='curriculum-elective'] .curriculum-requirement[data-coverage-status=\"VERIFIED\"]")).toHaveCount(3);await mobile.screenshot({path:"artifacts/curriculum/grade-12/grade-12-coverage-mobile.png",fullPage:true});
  const enLesson=enElective.requirements.find(x=>x.id==="g12-belief-and-religion-vietnam")!.lessons[0];await openLessonByKeyboard(mobile,enLesson);await expect(mobile).toHaveURL(`${baseURL}/en/topics/${enLesson.slug}`);await expect(mobile.getByRole("heading",{level:1,name:enLesson.title,exact:true})).toBeVisible();const enDetail=(await(await mobile.request.get(`${baseURL}/api/v1/en/contents/TOPIC/${enLesson.slug}`)).json()).data as DetailView;expect(enDetail).toMatchObject({id:enLesson.id,asOf:"2026-08-13T00:00:00.000Z",reviewedBy:expect.stringContaining("C-034")});expect(enDetail.claims).toHaveLength(2);expect(enDetail.sources.every(x=>x.verificationStatus==="VERIFIED")).toBe(true);const enSource=mobile.locator(".sources li").first().getByRole("link");await enSource.focus();await expect(enSource).toBeFocused();const mobileAxe=await blockingAxe(mobile);const mobileMetrics=await metrics(mobile);expect(mobileAxe).toEqual([]);expect(mobileMetrics.scrollWidth).toBe(mobileMetrics.clientWidth);expect(mobileMetrics.lcpMs).toBeLessThanOrEqual(2500);await mobile.screenshot({path:"artifacts/curriculum/grade-12/grade-12-mobile.png",fullPage:true});await mobileContext.close();
  await writeFile("artifacts/curriculum/grade-12/grade-12-proof.json",`${JSON.stringify({generatedAt:new Date().toISOString(),url:new URL(baseURL).origin,asOf:"2026-08-13T00:00:00.000Z",coverage:{mandatory:6,elective:3,locales:["vi","en"],trackLabelsSeparated:true},desktop:{path:`/vi/chu-de/${viLesson.slug}`,claims:viDetail.claims.length,keyboard:true,metrics:desktopMetrics},mobile:{path:`/en/topics/${enLesson.slug}`,claims:enDetail.claims.length,keyboard:true,metrics:mobileMetrics},accessibility:{desktopCriticalOrSerious:desktopAxe.length,mobileCriticalOrSerious:mobileAxe.length},screenshots:["artifacts/curriculum/grade-12/grade-12-coverage-desktop.png","artifacts/curriculum/grade-12/grade-12-desktop.png","artifacts/curriculum/grade-12/grade-12-coverage-mobile.png","artifacts/curriculum/grade-12/grade-12-mobile.png"]},null,2)}\\n`);
});
