import { resolve } from "node:path";
import { mkdir,writeFile } from "node:fs/promises";
import { expect,test,type Page } from "@playwright/test";

type ContentType="PERIOD"|"EVENT"|"PERSON"|"ARTIFACT"|"TOPIC";
type ContentItem={id:string;type:ContentType;title:string;slug:string};
const routes={vi:{PERIOD:"thoi-ky",EVENT:"su-kien",PERSON:"nhan-vat",ARTIFACT:"hien-vat",TOPIC:"chu-de"},en:{PERIOD:"periods",EVENT:"events",PERSON:"people",ARTIFACT:"artifacts",TOPIC:"topics"}} as const;
const types=Object.keys(routes.vi) as ContentType[];const axePath=resolve("node_modules/axe-core/axe.min.js");
const collectionPath=(locale:"vi"|"en",type:ContentType)=>`/${locale}/${routes[locale][type]}`;
const detailPath=(locale:"vi"|"en",item:ContentItem)=>`${collectionPath(locale,item.type)}/${item.slug}`;
async function blockingAxe(page:Page){await page.addScriptTag({path:axePath});return page.evaluate(async()=>{const axe=(window as unknown as {axe:{run:(root:Document,options:unknown)=>Promise<{violations:Array<{id:string;impact:string|null}>}>}}).axe;const result=await axe.run(document,{runOnly:{type:"tag",values:["wcag2a","wcag2aa","wcag21aa"]}});return result.violations.filter(({impact})=>impact==="critical"||impact==="serious");});}
async function trackLcp(page:Page){await page.addInitScript(()=>{(globalThis as typeof globalThis&{__collectionLcp?:number}).__collectionLcp=0;new PerformanceObserver((list)=>{for(const entry of list.getEntries())(globalThis as typeof globalThis&{__collectionLcp?:number}).__collectionLcp=Math.max((globalThis as typeof globalThis&{__collectionLcp?:number}).__collectionLcp??0,entry.startTime);}).observe({type:"largest-contentful-paint",buffered:true});});}
async function metrics(page:Page){return page.evaluate(()=>({clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,lcpMs:(globalThis as typeof globalThis&{__collectionLcp?:number}).__collectionLcp??0}));}

test("home collection links expose every published content type",async({browser,baseURL})=>{
  test.setTimeout(120_000);if(!baseURL)throw new Error("baseURL is required");await mkdir("artifacts/collections",{recursive:true});
  const routeProof:Record<string,{page:number;apiItems:number;allItemsMatchType:boolean}>={};
  const requestContext=await browser.newContext();const request=await requestContext.newPage();for(const locale of ["vi","en"] as const){for(const type of types){const path=collectionPath(locale,type);const [pageResponse,apiResponse]=await Promise.all([request.request.get(`${baseURL}${path}`),request.request.get(`${baseURL}/api/v1/${locale}/contents?type=${type}&page=1&pageSize=12&sort=${type==="PERIOD"||type==="EVENT"?"chronology":"title"}`)]);expect(pageResponse.ok()).toBe(true);expect(apiResponse.ok()).toBe(true);const api=await apiResponse.json() as {data:ContentItem[];meta:{page:number}};expect(api.data.every((item)=>item.type===type)).toBe(true);routeProof[`${locale}:${type}`]={page:api.meta.page,apiItems:api.data.length,allItemsMatchType:true};}}
  const sitemap=await (await request.request.get(`${baseURL}/sitemap.xml`)).text();for(const locale of ["vi","en"] as const)for(const type of types)expect(sitemap).toContain(`${baseURL}${collectionPath(locale,type)}`);expect(sitemap).not.toMatch(/\/api\/|\/admin|\?type=/);await requestContext.close();

  const desktopContext=await browser.newContext({viewport:{width:1440,height:1000}});const desktop=await desktopContext.newPage();await trackLcp(desktop);await desktop.goto(`${baseURL}/vi`,{waitUntil:"networkidle"});const homeLinks=desktop.locator(".pulse-strip > a");await expect(homeLinks).toHaveCount(4);for(const type of ["PERIOD","EVENT","PERSON","ARTIFACT"] as const)await expect(desktop.locator(`.pulse-strip > a[href="${collectionPath("vi",type)}"]`)).toHaveCount(1);
  const eventHomeLink=desktop.locator(`.pulse-strip > a[href="${collectionPath("vi","EVENT")}"]`);await eventHomeLink.click();await expect(desktop).toHaveURL(`${baseURL}/vi/su-kien`);await expect(desktop.getByRole("heading",{level:1,name:"Sự kiện và chiến dịch"})).toBeVisible();const viApi=await (await desktop.request.get(`${baseURL}/api/v1/vi/contents?type=EVENT&page=1&pageSize=12&sort=chronology`)).json() as {data:ContentItem[]};await expect(desktop.locator(".collection-grid .content-card")).toHaveCount(viApi.data.length);const viFirst=viApi.data[0];await desktop.getByRole("link",{name:viFirst.title,exact:true}).click();await expect(desktop).toHaveURL(`${baseURL}${detailPath("vi",viFirst)}`);const viBreadcrumb=desktop.locator(".breadcrumbs").getByRole("link").nth(1);await expect(viBreadcrumb).toHaveAttribute("href",collectionPath("vi","EVENT"));await viBreadcrumb.click();await expect(desktop).toHaveURL(`${baseURL}/vi/su-kien`);await desktop.getByRole("link",{name:"Chuyển sang tiếng Anh"}).click();await expect(desktop).toHaveURL(`${baseURL}/en/events`);const desktopAxe=await blockingAxe(desktop);expect(desktopAxe).toEqual([]);await desktop.waitForTimeout(400);const desktopMetrics=await metrics(desktop);expect(desktopMetrics.scrollWidth).toBe(desktopMetrics.clientWidth);expect(desktopMetrics.lcpMs).toBeLessThanOrEqual(2500);await desktop.emulateMedia({reducedMotion:"reduce"});await desktop.screenshot({path:"artifacts/collections/collections-desktop.png",fullPage:true});await desktopContext.close();

  const mobileContext=await browser.newContext({viewport:{width:390,height:844}});const mobile=await mobileContext.newPage();await trackLcp(mobile);await mobile.goto(`${baseURL}/en`,{waitUntil:"networkidle"});const peopleLink=mobile.locator(`.pulse-strip > a[href="${collectionPath("en","PERSON")}"]`);await peopleLink.focus();await mobile.keyboard.press("Enter");await expect(mobile).toHaveURL(`${baseURL}/en/people`);await expect(mobile.getByRole("heading",{level:1,name:"People"})).toBeVisible();const enApi=await (await mobile.request.get(`${baseURL}/api/v1/en/contents?type=PERSON&page=1&pageSize=12&sort=title`)).json() as {data:ContentItem[]};const enFirst=enApi.data[0];const enLink=mobile.getByRole("link",{name:enFirst.title,exact:true});await enLink.focus();await mobile.keyboard.press("Enter");await expect(mobile).toHaveURL(`${baseURL}${detailPath("en",enFirst)}`);await mobile.locator(".breadcrumbs").getByRole("link").nth(1).focus();await mobile.keyboard.press("Enter");await expect(mobile).toHaveURL(`${baseURL}/en/people`);const mobileAxe=await blockingAxe(mobile);expect(mobileAxe).toEqual([]);await mobile.waitForTimeout(400);const mobileMetrics=await metrics(mobile);expect(mobileMetrics.scrollWidth).toBe(mobileMetrics.clientWidth);expect(mobileMetrics.lcpMs).toBeLessThanOrEqual(2500);await mobile.emulateMedia({reducedMotion:"reduce"});await mobile.screenshot({path:"artifacts/collections/collections-mobile.png",fullPage:true});await mobileContext.close();

  const proof={generatedAt:new Date().toISOString(),url:new URL(baseURL).origin,routes:routeProof,homeLinks:["PERIOD","EVENT","PERSON","ARTIFACT"],sitemapCollections:10,pointer:{from:"/vi",collection:"/vi/su-kien",detail:detailPath("vi",viFirst),breadcrumb:"/vi/su-kien",localeSwitch:"/en/events"},keyboard:{from:"/en",collection:"/en/people",detail:detailPath("en",enFirst),breadcrumb:"/en/people"},accessibility:{desktopCriticalOrSerious:desktopAxe.length,mobileCriticalOrSerious:mobileAxe.length},desktopMetrics,mobileMetrics,screenshots:["artifacts/collections/collections-desktop.png","artifacts/collections/collections-mobile.png"]};await writeFile("artifacts/collections/collections-proof.json",`${JSON.stringify(proof,null,2)}\n`);
});
