import { resolve } from "node:path";
import { mkdir,writeFile } from "node:fs/promises";
import { expect,test,type Page } from "@playwright/test";

type ContentRef={id:string;type:"PERIOD"|"EVENT"|"PERSON"|"ARTIFACT"|"TOPIC";title:string;slug:string};
type SourceItem={url:string;title:string;contentCount:number;contents:ContentRef[]};
const segments={vi:{PERIOD:"thoi-ky",EVENT:"su-kien",PERSON:"nhan-vat",ARTIFACT:"hien-vat",TOPIC:"chu-de"},en:{PERIOD:"periods",EVENT:"events",PERSON:"people",ARTIFACT:"artifacts",TOPIC:"topics"}} as const;
const axePath=resolve("node_modules/axe-core/axe.min.js");
const publicPath=(locale:"vi"|"en",item:ContentRef)=>`/${locale}/${segments[locale][item.type]}/${item.slug}`;
async function blockingAxe(page:Page){await page.addScriptTag({path:axePath});return page.evaluate(async()=>{const axe=(window as unknown as {axe:{run:(root:Document,options:unknown)=>Promise<{violations:Array<{id:string;impact:string|null}>}>}}).axe;const result=await axe.run(document,{runOnly:{type:"tag",values:["wcag2a","wcag2aa","wcag21aa"]}});return result.violations.filter(({impact})=>impact==="critical"||impact==="serious");});}
async function trackLcp(page:Page){await page.addInitScript(()=>{(globalThis as typeof globalThis&{__usageLcp?:number}).__usageLcp=0;new PerformanceObserver((list)=>{for(const entry of list.getEntries())(globalThis as typeof globalThis&{__usageLcp?:number}).__usageLcp=Math.max((globalThis as typeof globalThis&{__usageLcp?:number}).__usageLcp??0,entry.startTime);}).observe({type:"largest-contentful-paint",buffered:true});});}
async function metrics(page:Page){return page.evaluate(()=>({clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,lcpMs:(globalThis as typeof globalThis&{__usageLcp?:number}).__usageLcp??0}));}
function showcase(items:SourceItem[]){return [...items].filter(({contentCount})=>contentCount>1&&contentCount<=8).sort((a,b)=>b.contentCount-a.contentCount)[0]??items.find(({contentCount})=>contentCount>1)??items[0];}
function localeCoverage(items:SourceItem[]){return {sources:items.length,totalContentLinks:items.reduce((sum,source)=>sum+source.contents.length,0),allCountsMatch:items.every((source)=>source.contentCount===source.contents.length),allContentIdsUnique:items.every((source)=>new Set(source.contents.map(({id})=>id)).size===source.contents.length)};}
async function publishedRoutesResolve(page:Page,baseURL:string,locale:"vi"|"en",items:SourceItem[]){const paths=[...new Set(items.flatMap((source)=>source.contents.map((item)=>publicPath(locale,item))))];const responses=await Promise.all(paths.map((path)=>page.request.get(`${baseURL}${path}`)));return {count:paths.length,allResolve:responses.every((response)=>response.ok())};}

test("source usage disclosures reach published details by pointer and keyboard",async({browser,baseURL})=>{
  test.setTimeout(120_000);if(!baseURL)throw new Error("baseURL is required");await mkdir("artifacts/source-usage",{recursive:true});
  const desktopContext=await browser.newContext({viewport:{width:1440,height:1000}});const desktop=await desktopContext.newPage();await trackLcp(desktop);await desktop.goto(`${baseURL}/vi/sources`,{waitUntil:"networkidle"});
  const viApi=await (await desktop.request.get(`${baseURL}/api/v1/vi/sources?pageSize=20`)).json() as {data:SourceItem[]};const viCoverage=localeCoverage(viApi.data);expect(viCoverage.allCountsMatch).toBe(true);expect(viCoverage.allContentIdsUnique).toBe(true);const viPublishedRoutes=await publishedRoutesResolve(desktop,baseURL,"vi",viApi.data);expect(viPublishedRoutes.allResolve).toBe(true);
  const viSource=showcase(viApi.data);const viRow=desktop.locator(".source-directory-item").filter({hasText:viSource.title}).first();const viDetails=viRow.locator("details");await viDetails.locator("summary").click();await expect(viDetails).toHaveAttribute("open","");await expect(viDetails.locator("li")).toHaveCount(viSource.contentCount);
  const viFirst=viSource.contents[0];const viHref=publicPath("vi",viFirst);await expect(viDetails.getByRole("link",{name:viFirst.title,exact:true})).toHaveAttribute("href",viHref);const desktopAxe=await blockingAxe(desktop);expect(desktopAxe).toEqual([]);await desktop.waitForTimeout(400);const desktopMetrics=await metrics(desktop);expect(desktopMetrics.scrollWidth).toBe(desktopMetrics.clientWidth);expect(desktopMetrics.lcpMs).toBeLessThanOrEqual(2500);await desktop.screenshot({path:"artifacts/source-usage/source-usage-desktop.png",fullPage:true});
  await viDetails.getByRole("link",{name:viFirst.title,exact:true}).click();await expect(desktop).toHaveURL(`${baseURL}${viHref}`);await expect(desktop.getByRole("heading",{level:1,name:viFirst.title,exact:true})).toBeVisible();await desktop.goBack({waitUntil:"networkidle"});await expect(desktop).toHaveURL(`${baseURL}/vi/sources`);await desktopContext.close();

  const mobileContext=await browser.newContext({viewport:{width:390,height:844}});const mobile=await mobileContext.newPage();await trackLcp(mobile);await mobile.goto(`${baseURL}/en/sources`,{waitUntil:"networkidle"});const enApi=await (await mobile.request.get(`${baseURL}/api/v1/en/sources?pageSize=20`)).json() as {data:SourceItem[]};const enCoverage=localeCoverage(enApi.data);expect(enCoverage.allCountsMatch).toBe(true);expect(enCoverage.allContentIdsUnique).toBe(true);const enPublishedRoutes=await publishedRoutesResolve(mobile,baseURL,"en",enApi.data);expect(enPublishedRoutes.allResolve).toBe(true);const enSource=showcase(enApi.data);const enRow=mobile.locator(".source-directory-item").filter({hasText:enSource.title}).first();const enDetails=enRow.locator("details");const summary=enDetails.locator("summary");await summary.focus();await mobile.keyboard.press("Enter");await expect(enDetails).toHaveAttribute("open","");await expect(enDetails.locator("li")).toHaveCount(enSource.contentCount);
  const enFirst=enSource.contents[0];const enHref=publicPath("en",enFirst);const enLink=enDetails.getByRole("link",{name:enFirst.title,exact:true});await expect(enLink).toHaveAttribute("href",enHref);const mobileAxe=await blockingAxe(mobile);expect(mobileAxe).toEqual([]);await mobile.waitForTimeout(400);const mobileMetrics=await metrics(mobile);expect(mobileMetrics.scrollWidth).toBe(mobileMetrics.clientWidth);expect(mobileMetrics.lcpMs).toBeLessThanOrEqual(2500);await mobile.screenshot({path:"artifacts/source-usage/source-usage-mobile.png",fullPage:true});await enLink.focus();await mobile.keyboard.press("Enter");await expect(mobile).toHaveURL(`${baseURL}${enHref}`);await mobile.goBack({waitUntil:"networkidle"});await expect(mobile).toHaveURL(`${baseURL}/en/sources`);await mobileContext.close();

  const proof={generatedAt:new Date().toISOString(),url:new URL(baseURL).origin,locales:{vi:{...viCoverage,publishedRoutes:viPublishedRoutes},en:{...enCoverage,publishedRoutes:enPublishedRoutes}},pointer:{source:viSource.title,count:viSource.contentCount,href:viHref,back:"/vi/sources"},keyboard:{source:enSource.title,count:enSource.contentCount,href:enHref,back:"/en/sources"},accessibility:{desktopCriticalOrSerious:desktopAxe.length,mobileCriticalOrSerious:mobileAxe.length},desktopMetrics,mobileMetrics,screenshots:["artifacts/source-usage/source-usage-desktop.png","artifacts/source-usage/source-usage-mobile.png"]};await writeFile("artifacts/source-usage/source-usage-proof.json",`${JSON.stringify(proof,null,2)}\n`);
});
