import { resolve } from "node:path";
import { mkdir,writeFile } from "node:fs/promises";
import { expect,test,type Page } from "@playwright/test";

type Locale="vi"|"en";type ContentType="EVENT"|"ARTIFACT";
type Period={id:string;title:string;slug:string};type Item={id:string;title:string;slug:string;type:ContentType};
const axePath=resolve("node_modules/axe-core/axe.min.js");
const paths={vi:{EVENT:"/vi/su-kien",ARTIFACT:"/vi/hien-vat"},en:{EVENT:"/en/events",ARTIFACT:"/en/artifacts"}} as const;
async function blockingAxe(page:Page){await page.addScriptTag({path:axePath});return page.evaluate(async()=>{const axe=(window as unknown as {axe:{run:(root:Document,options:unknown)=>Promise<{violations:Array<{id:string;impact:string|null}>}>}}).axe;const result=await axe.run(document,{runOnly:{type:"tag",values:["wcag2a","wcag2aa","wcag21aa"]}});return result.violations.filter(({impact})=>impact==="critical"||impact==="serious");});}
async function trackLcp(page:Page){await page.addInitScript(()=>{(globalThis as typeof globalThis&{__filterLcp?:number}).__filterLcp=0;new PerformanceObserver((list)=>{for(const entry of list.getEntries())(globalThis as typeof globalThis&{__filterLcp?:number}).__filterLcp=Math.max((globalThis as typeof globalThis&{__filterLcp?:number}).__filterLcp??0,entry.startTime);}).observe({type:"largest-contentful-paint",buffered:true});});}
async function metrics(page:Page){return page.evaluate(()=>({clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,lcpMs:(globalThis as typeof globalThis&{__filterLcp?:number}).__filterLcp??0}));}
async function apiItems(page:Page,baseURL:string,locale:Locale,type:ContentType,period:string,sort:string){const response=await page.request.get(`${baseURL}/api/v1/${locale}/contents?type=${type}&period=${encodeURIComponent(period)}&sort=${sort}&page=1&pageSize=12`);expect(response.ok()).toBe(true);return response.json() as Promise<{data:Item[];meta:{total:number;totalPages:number}}>;}
async function periodWithContent(page:Page,baseURL:string,locale:Locale,type:ContentType){const response=await page.request.get(`${baseURL}/api/v1/${locale}/periods?includeEmpty=true`);expect(response.ok()).toBe(true);const periods=(await response.json() as {data:Period[]}).data;for(let index=0;index<periods.length;index++){const result=await apiItems(page,baseURL,locale,type,periods[index].slug,"title");if(result.data.length)return{period:periods[index],index,items:result.data};}throw new Error(`No ${type} period with published content for ${locale}`);}

test("collection filters survive pagination, history, copy, and locale switch",async({browser,baseURL})=>{
  test.setTimeout(120_000);if(!baseURL)throw new Error("baseURL is required");await mkdir("artifacts/collection-filters",{recursive:true});
  const desktopContext=await browser.newContext({viewport:{width:1440,height:1000}});const desktop=await desktopContext.newPage();await trackLcp(desktop);const viEvent=await periodWithContent(desktop,baseURL,"vi","EVENT");const enPeriods=(await (await desktop.request.get(`${baseURL}/api/v1/en/periods?includeEmpty=true`)).json() as {data:Period[]}).data;const enEventPeriod=enPeriods.find(({id})=>id===viEvent.period.id);expect(enEventPeriod).toBeTruthy();
  await desktop.goto(`${baseURL}${paths.vi.EVENT}?sort=khong-hop-le&period=khong-ton-tai`,{waitUntil:"networkidle"});await expect(desktop.locator("#collection-sort")).toHaveValue("chronology");await expect(desktop.locator("#collection-period")).toHaveValue("");const unfiltered=await desktop.request.get(`${baseURL}/api/v1/vi/contents?type=EVENT&sort=chronology&page=1&pageSize=12`);expect(unfiltered.ok()).toBe(true);const unfilteredBody=await unfiltered.json() as {data:Item[]};await expect(desktop.locator(".collection-grid .content-card")).toHaveCount(unfilteredBody.data.length);
  await desktop.goto(`${baseURL}${paths.vi.EVENT}`,{waitUntil:"networkidle"});await desktop.locator("#collection-sort").selectOption("title");await desktop.getByRole("button",{name:"Áp dụng"}).click();await expect(desktop).toHaveURL(/sort=title/);let url=new URL(desktop.url());expect(url.searchParams.get("sort")).toBe("title");const next=desktop.getByRole("link",{name:"Trang sau"});await expect(next).toHaveAttribute("href",/sort=title/);await next.click();await expect(desktop).toHaveURL(/page=2/);await desktop.goBack({waitUntil:"networkidle"});expect(new URL(desktop.url()).searchParams.get("page")).toBeNull();await desktop.goForward({waitUntil:"networkidle"});await expect(desktop).toHaveURL(/page=2/);await desktop.goBack({waitUntil:"networkidle"});
  await desktop.locator("#collection-period").selectOption(viEvent.period.slug);await desktop.getByRole("button",{name:"Áp dụng"}).click();url=new URL(desktop.url());expect(url.searchParams.get("period")).toBe(viEvent.period.slug);expect(url.searchParams.get("sort")).toBe("title");const viFiltered=await apiItems(desktop,baseURL,"vi","EVENT",viEvent.period.slug,"title");await expect(desktop.locator(".collection-grid .content-card")).toHaveCount(viFiltered.data.length);const copiedUrl=desktop.url();const copied=await desktopContext.newPage();await copied.goto(copiedUrl,{waitUntil:"networkidle"});await expect(copied.locator("#collection-period")).toHaveValue(viEvent.period.slug);await expect(copied.locator("#collection-sort")).toHaveValue("title");await copied.close();
  const firstEvent=viFiltered.data[0];await desktop.getByRole("link",{name:firstEvent.title,exact:true}).click();await expect(desktop).toHaveURL(`${baseURL}${paths.vi.EVENT}/${firstEvent.slug}`);await desktop.goBack({waitUntil:"networkidle"});expect(desktop.url()).toBe(copiedUrl);await desktop.getByRole("link",{name:"Chuyển sang tiếng Anh"}).click();await expect(desktop).toHaveURL(/\/en\/events/);url=new URL(desktop.url());expect(url.pathname).toBe(paths.en.EVENT);expect(url.searchParams.get("period")).toBe(enEventPeriod!.slug);expect(url.searchParams.get("sort")).toBe("title");const enFiltered=await apiItems(desktop,baseURL,"en","EVENT",enEventPeriod!.slug,"title");await expect(desktop.locator(".collection-grid .content-card")).toHaveCount(enFiltered.data.length);const desktopAxe=await blockingAxe(desktop);expect(desktopAxe).toEqual([]);await desktop.waitForTimeout(400);const desktopMetrics=await metrics(desktop);expect(desktopMetrics.scrollWidth).toBe(desktopMetrics.clientWidth);expect(desktopMetrics.lcpMs).toBeLessThanOrEqual(2500);await desktop.emulateMedia({reducedMotion:"reduce"});await desktop.screenshot({path:"artifacts/collection-filters/collection-filters-desktop.png",fullPage:true});await desktopContext.close();

  const mobileContext=await browser.newContext({viewport:{width:390,height:844}});const mobile=await mobileContext.newPage();await trackLcp(mobile);const enArtifact=await periodWithContent(mobile,baseURL,"en","ARTIFACT");await mobile.goto(`${baseURL}${paths.en.ARTIFACT}`,{waitUntil:"networkidle"});const sortSelect=mobile.locator("#collection-sort");await sortSelect.selectOption("updated");await expect(sortSelect).toHaveValue("updated");const periodSelect=mobile.locator("#collection-period");await periodSelect.selectOption(enArtifact.period.slug);await expect(periodSelect).toHaveValue(enArtifact.period.slug);const apply=mobile.getByRole("button",{name:"Apply"});await apply.focus();await mobile.keyboard.press("Enter");await expect(mobile).toHaveURL(/sort=updated/);url=new URL(mobile.url());expect(url.searchParams.get("period")).toBe(enArtifact.period.slug);expect(url.searchParams.get("sort")).toBe("updated");const mobileFilteredUrl=mobile.url();const mobileFiltered=await apiItems(mobile,baseURL,"en","ARTIFACT",enArtifact.period.slug,"updated");await expect(mobile.locator(".collection-grid .content-card")).toHaveCount(mobileFiltered.data.length);const firstArtifact=mobileFiltered.data[0];const artifactLink=mobile.getByRole("link",{name:firstArtifact.title,exact:true});await artifactLink.focus();await mobile.keyboard.press("Enter");await expect(mobile).toHaveURL(`${baseURL}${paths.en.ARTIFACT}/${firstArtifact.slug}`);await mobile.goBack({waitUntil:"networkidle"});const mobileAxe=await blockingAxe(mobile);expect(mobileAxe).toEqual([]);await mobile.waitForTimeout(400);const mobileMetrics=await metrics(mobile);expect(mobileMetrics.scrollWidth).toBe(mobileMetrics.clientWidth);expect(mobileMetrics.lcpMs).toBeLessThanOrEqual(2500);await mobile.goto(mobileFilteredUrl,{waitUntil:"networkidle"});await mobile.emulateMedia({reducedMotion:"reduce"});await mobile.screenshot({path:"artifacts/collection-filters/collection-filters-mobile.png",fullPage:true});await mobileContext.close();

  const proof={generatedAt:new Date().toISOString(),url:new URL(baseURL).origin,invalidQueryFallback:{sort:"chronology",period:null,apiItems:unfilteredBody.data.length},periodMapping:{id:viEvent.period.id,viSlug:viEvent.period.slug,enSlug:enEventPeriod!.slug},pointer:{sort:"title",paginationBackForward:true,period:viEvent.period.slug,copiedUrl,copyRestored:true,detail:`${paths.vi.EVENT}/${firstEvent.slug}`,localeSwitch:`${paths.en.EVENT}?period=${enEventPeriod!.slug}&sort=title`,apiItems:enFiltered.data.length},keyboard:{sort:"updated",period:enArtifact.period.slug,collection:paths.en.ARTIFACT,detail:`${paths.en.ARTIFACT}/${firstArtifact.slug}`,apiItems:mobileFiltered.data.length},accessibility:{desktopCriticalOrSerious:desktopAxe.length,mobileCriticalOrSerious:mobileAxe.length},desktopMetrics,mobileMetrics,screenshots:["artifacts/collection-filters/collection-filters-desktop.png","artifacts/collection-filters/collection-filters-mobile.png"]};await writeFile("artifacts/collection-filters/collection-filters-proof.json",`${JSON.stringify(proof,null,2)}\n`);
});
