import { resolve } from "node:path";
import { mkdir,writeFile } from "node:fs/promises";
import { expect,test,type Page } from "@playwright/test";

const axePath=resolve("node_modules/axe-core/axe.min.js");
async function blockingAxe(page:Page){await page.addScriptTag({path:axePath});return page.evaluate(async()=>{const axe=(window as unknown as {axe:{run:(root:Document,options:unknown)=>Promise<{violations:Array<{id:string;impact:string|null}>}>}}).axe;const result=await axe.run(document,{runOnly:{type:"tag",values:["wcag2a","wcag2aa","wcag21aa"]}});return result.violations.filter(({impact})=>impact==="critical"||impact==="serious");});}
async function trackLcp(page:Page){await page.addInitScript(()=>{(globalThis as typeof globalThis&{__entryLcp?:number}).__entryLcp=0;new PerformanceObserver((list)=>{for(const entry of list.getEntries())(globalThis as typeof globalThis&{__entryLcp?:number}).__entryLcp=Math.max((globalThis as typeof globalThis&{__entryLcp?:number}).__entryLcp??0,entry.startTime);}).observe({type:"largest-contentful-paint",buffered:true});});}
async function metrics(page:Page){return page.evaluate(()=>({clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,lcpMs:(globalThis as typeof globalThis&{__entryLcp?:number}).__entryLcp??0}));}

test("public footer explains and opens the protected editorial workspace",async({browser,baseURL})=>{
  test.setTimeout(120_000);if(!baseURL)throw new Error("baseURL is required");await mkdir("artifacts/editorial-entry",{recursive:true});
  const desktopContext=await browser.newContext({viewport:{width:1440,height:1000}});const desktop=await desktopContext.newPage();await trackLcp(desktop);await desktop.goto(`${baseURL}/vi`,{waitUntil:"networkidle"});const viEntry=desktop.getByRole("link",{name:"Đăng nhập không gian biên tập"});await expect(viEntry).toHaveAttribute("href","/admin/login");await expect(desktop.locator(".footer-editorial")).toContainText("Tài khoản do quản trị viên cấp; không có đăng ký công khai.");await desktop.waitForTimeout(400);const desktopAxe=await blockingAxe(desktop);expect(desktopAxe).toEqual([]);const desktopMetrics=await metrics(desktop);expect(desktopMetrics.scrollWidth).toBe(desktopMetrics.clientWidth);expect(desktopMetrics.lcpMs).toBeLessThanOrEqual(2500);await desktop.locator(".site-footer").screenshot({path:"artifacts/editorial-entry/editorial-entry-desktop.png"});await viEntry.click();await expect(desktop).toHaveURL(`${baseURL}/admin/login`);await expect(desktop.getByRole("heading",{level:1,name:"Đăng nhập để tiếp tục"})).toBeVisible();await expect(desktop.locator('meta[name="robots"]')).toHaveAttribute("content",/noindex/);await expect(desktop.getByRole("link",{name:/đăng ký|register|sign up/i})).toHaveCount(0);await desktop.goBack({waitUntil:"networkidle"});await expect(desktop).toHaveURL(`${baseURL}/vi`);await desktop.goto(`${baseURL}/admin`,{waitUntil:"networkidle"});await expect(desktop).toHaveURL(`${baseURL}/admin/login`);await desktopContext.close();

  const mobileContext=await browser.newContext({viewport:{width:390,height:844}});const mobile=await mobileContext.newPage();await trackLcp(mobile);await mobile.goto(`${baseURL}/en`,{waitUntil:"networkidle"});const enEntry=mobile.getByRole("link",{name:"Sign in to the editorial workspace"});await expect(enEntry).toHaveAttribute("href","/admin/login");await expect(mobile.locator(".footer-editorial")).toContainText("Accounts are issued by an administrator; public registration is not available.");await mobile.waitForTimeout(400);const mobileAxe=await blockingAxe(mobile);expect(mobileAxe).toEqual([]);const mobileMetrics=await metrics(mobile);expect(mobileMetrics.scrollWidth).toBe(mobileMetrics.clientWidth);expect(mobileMetrics.lcpMs).toBeLessThanOrEqual(2500);await mobile.locator(".site-footer").screenshot({path:"artifacts/editorial-entry/editorial-entry-mobile.png"});await enEntry.focus();await mobile.keyboard.press("Enter");await expect(mobile).toHaveURL(`${baseURL}/admin/login`);await mobile.goBack({waitUntil:"networkidle"});await expect(mobile).toHaveURL(`${baseURL}/en`);await mobileContext.close();

  const [sitemap,register,adminRegister]=await Promise.all([fetch(`${baseURL}/sitemap.xml`).then((response)=>response.text()),fetch(`${baseURL}/register`),fetch(`${baseURL}/admin/register`)]);expect(sitemap).not.toMatch(/\/admin/);expect(register.status).toBe(404);expect(adminRegister.status).toBe(404);
  const proof={generatedAt:new Date().toISOString(),url:new URL(baseURL).origin,vi:{href:"/admin/login",copy:"Tài khoản do quản trị viên cấp; không có đăng ký công khai.",pointer:true,back:"/vi"},en:{href:"/admin/login",copy:"Accounts are issued by an administrator; public registration is not available.",keyboard:true,back:"/en"},protection:{unauthenticatedAdminRedirect:"/admin/login",loginNoindex:true,sitemapExcludesAdmin:true,registerStatus:register.status,adminRegisterStatus:adminRegister.status},accessibility:{desktopCriticalOrSerious:desktopAxe.length,mobileCriticalOrSerious:mobileAxe.length},desktopMetrics,mobileMetrics,screenshots:["artifacts/editorial-entry/editorial-entry-desktop.png","artifacts/editorial-entry/editorial-entry-mobile.png"]};await writeFile("artifacts/editorial-entry/editorial-entry-proof.json",`${JSON.stringify(proof,null,2)}\n`);
});
