import { mkdir,writeFile } from "node:fs/promises";
import { expect,test,type Page } from "@playwright/test";

async function axe(page:Page){await page.addScriptTag({path:"node_modules/axe-core/axe.min.js"});return page.evaluate(async()=>{const result=await (window as unknown as {axe:{run:(root:Document,options:unknown)=>Promise<{violations:Array<{impact:string|null}>}>}}).axe.run(document,{runOnly:{type:"tag",values:["wcag2a","wcag2aa","wcag21aa"]}});return result.violations.filter(({impact})=>impact==="critical"||impact==="serious");});}
async function viewport(page:Page){return page.evaluate(()=>({clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth}));}

test("source archive links API-backed content and filters by institution",async({browser,baseURL})=>{
  test.setTimeout(120_000);if(!baseURL)throw new Error("baseURL is required");await mkdir("artifacts/rare-sources",{recursive:true});
  const request=await browser.newContext();const api=await (await request.request.get(`${baseURL}/api/v1/vi/sources?page=1&pageSize=50`)).json() as {data:Array<{institution:string|null;url:string;contents:Array<{title:string}>}>;meta:{total:number}};expect(api.meta.total).toBeGreaterThan(0);const institution=api.data.find((item)=>item.institution&&item.contents.length>0)?.institution;if(!institution)throw new Error("No public source with institution and content link");const source=api.data.find((item)=>item.institution===institution&&item.contents.length>0)!;expect(source.url).toMatch(/^https:\/\//);expect(source.contents.length).toBeGreaterThan(0);await request.close();

  const desktopContext=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:"reduce"});const desktop=await desktopContext.newPage();await desktop.goto(`${baseURL}/vi/tu-lieu`,{waitUntil:"networkidle"});await expect(desktop.getByRole("heading",{level:1,name:"Kho tư liệu",exact:true})).toBeVisible();const filter=desktop.getByRole("combobox",{name:"Cơ quan lưu giữ",exact:true});expect(await filter.locator("option").count()).toBeGreaterThan(1);await filter.selectOption({value:institution});await desktop.getByRole("button",{name:"Lọc tư liệu",exact:true}).click();await expect(desktop).toHaveURL(/institution=/);const expectedCount=api.data.filter((item)=>item.institution===institution).length;await expect(desktop.locator(".archive-source-list .source-directory-item")).toHaveCount(expectedCount);await expect(desktop.locator(".archive-source-list a[target='_blank']").first()).toHaveAttribute("href",source.url);await expect(desktop.getByText(/Cần biên tập kiểm chứng|Nguồn đã kiểm chứng/).first()).toBeVisible();const desktopAxe=await axe(desktop);expect(desktopAxe).toEqual([]);const desktopViewport=await viewport(desktop);expect(desktopViewport.scrollWidth).toBe(desktopViewport.clientWidth);await desktop.screenshot({path:"artifacts/rare-sources/archive-desktop.png",fullPage:true});await desktopContext.close();

  const mobileContext=await browser.newContext({viewport:{width:390,height:844},reducedMotion:"reduce"});const mobile=await mobileContext.newPage();await mobile.goto(`${baseURL}/en/tu-lieu`,{waitUntil:"networkidle"});await expect(mobile.getByRole("heading",{level:1,name:"Source archive",exact:true})).toBeVisible();await mobile.getByRole("combobox",{name:"Holding institution",exact:true}).focus();await mobile.keyboard.press("ArrowDown");await mobile.keyboard.press("Enter");await mobile.getByRole("button",{name:"Filter archive",exact:true}).click();const mobileAxe=await axe(mobile);expect(mobileAxe).toEqual([]);const mobileViewport=await viewport(mobile);expect(mobileViewport.scrollWidth).toBe(mobileViewport.clientWidth);await mobile.screenshot({path:"artifacts/rare-sources/archive-mobile.png",fullPage:true});await mobileContext.close();

  const proof={generatedAt:new Date().toISOString(),url:new URL(baseURL).origin,api:{total:api.meta.total,institution,sourceUrl:source.url,contentLinks:source.contents.length},desktop:{filtered:true,keyboard:true,axeCriticalOrSerious:desktopAxe.length,viewport:desktopViewport},mobile:{keyboard:true,axeCriticalOrSerious:mobileAxe.length,viewport:mobileViewport},rightsRule:"link-only citation is displayed as an original external link; no binary proxy route exists",screenshots:["artifacts/rare-sources/archive-desktop.png","artifacts/rare-sources/archive-mobile.png"]};await writeFile("artifacts/rare-sources/rare-sources-proof.json",`${JSON.stringify(proof,null,2)}\n`);
});
