import { mkdir,writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { expect,test,type Locator,type Page } from "@playwright/test";

type TimelineStyle={animationName:string;animationTimeline:string;opacity:string;scale:string;backgroundColor:string};
const axePath=resolve("node_modules/axe-core/axe.min.js");

async function style(locator:Locator,pseudo:string|null=null):Promise<TimelineStyle>{return locator.evaluate((element,pseudoElement)=>{const computed=getComputedStyle(element,pseudoElement);return{animationName:computed.animationName,animationTimeline:computed.getPropertyValue("animation-timeline"),opacity:computed.opacity,scale:computed.scale,backgroundColor:computed.backgroundColor};},pseudo);}
function scaleY(value:string){if(value==="none")return 1;const values=value.split(" ").map(Number);return values[1]??values[0]??1;}
async function scrollTimeline(page:Page,fraction:number){await page.evaluate((ratio)=>{const list=document.querySelector(".timeline-list");if(!list)return;const top=list.getBoundingClientRect().top+scrollY;scrollTo({top:top+list.scrollHeight*ratio-innerHeight/2,behavior:"instant"});},fraction);await page.waitForTimeout(250);}
async function closestEntry(page:Page){return page.locator(".timeline-entry").evaluateAll((entries)=>{let index=0;let distance=Number.POSITIVE_INFINITY;entries.forEach((entry,current)=>{const rect=entry.getBoundingClientRect();const next=Math.abs(rect.top+rect.height/2-innerHeight/2);if(next<distance){distance=next;index=current;}});return index;});}
async function blockingAxe(page:Page){await page.addScriptTag({path:axePath});return page.evaluate(async()=>{const axe=(window as unknown as {axe:{run:(root:Document,options:unknown)=>Promise<{violations:Array<{id:string;impact:string|null}>}>}}).axe;const result=await axe.run(document,{runOnly:{type:"tag",values:["wcag2a","wcag2aa","wcag21aa"]}});return result.violations.filter(({impact})=>impact==="critical"||impact==="serious");});}
async function addMetrics(page:Page){await page.addInitScript(()=>{const state=globalThis as typeof globalThis&{__timelineCls?:number;__timelineLcp?:number};state.__timelineCls=0;state.__timelineLcp=0;new PerformanceObserver((list)=>{for(const entry of list.getEntries()){const shift=entry as PerformanceEntry&{hadRecentInput?:boolean;value?:number};if(!shift.hadRecentInput)state.__timelineCls=(state.__timelineCls??0)+(shift.value??0);}}).observe({type:"layout-shift",buffered:true});new PerformanceObserver((list)=>{for(const entry of list.getEntries())state.__timelineLcp=Math.max(state.__timelineLcp??0,entry.startTime);}).observe({type:"largest-contentful-paint",buffered:true});});}

test("timeline progress follows reading position and disappears for reduced motion",async({browser,baseURL})=>{
  test.setTimeout(120_000);if(!baseURL)throw new Error("baseURL is required");await mkdir("artifacts/timeline-progress",{recursive:true});
  const desktopContext=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:"no-preference"});const desktop=await desktopContext.newPage();await addMetrics(desktop);await desktop.goto(`${baseURL}/vi/timeline`,{waitUntil:"networkidle"});await desktop.waitForTimeout(500);
  const list=desktop.locator(".timeline-list");const baseLine=await style(list,"::before");const start=await style(list,"::after");expect(start.animationName).toBe("timeline-progress");expect(start.animationTimeline).not.toBe("auto");expect(baseLine.backgroundColor).not.toBe("rgba(0, 0, 0, 0)");await scrollTimeline(desktop,.5);const middle=await style(list,"::after");const activeIndex=await closestEntry(desktop);const activeDot=await style(desktop.locator(".timeline-dot").nth(activeIndex));expect(activeDot.animationName).toBe("timeline-focus");expect(scaleY(activeDot.scale)).toBeGreaterThan(1.2);await desktop.screenshot({path:"artifacts/timeline-progress/desktop.png"});await scrollTimeline(desktop,.92);const end=await style(list,"::after");expect(scaleY(middle.scale)).toBeGreaterThan(scaleY(start.scale)+.15);expect(scaleY(end.scale)).toBeGreaterThan(scaleY(middle.scale)+.15);
  const metrics=await desktop.evaluate(()=>{const state=globalThis as typeof globalThis&{__timelineCls?:number;__timelineLcp?:number};return{cumulativeLayoutShift:state.__timelineCls??0,lcpMs:state.__timelineLcp??0,clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth};});expect(metrics.cumulativeLayoutShift).toBeLessThanOrEqual(.1);expect(metrics.lcpMs).toBeLessThanOrEqual(2500);expect(metrics.scrollWidth).toBe(metrics.clientWidth);expect(await blockingAxe(desktop)).toEqual([]);const activeLink=desktop.locator(".timeline-entry h2 a").nth(activeIndex);const href=await activeLink.getAttribute("href");if(!href)throw new Error("Active timeline entry is missing its detail link");await activeLink.focus();await expect(activeLink).toBeFocused();await activeLink.press("Enter");await expect(desktop).toHaveURL(new RegExp(`${href.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}$`));await desktopContext.close();

  const mobileContext=await browser.newContext({viewport:{width:390,height:844},reducedMotion:"no-preference"});const mobile=await mobileContext.newPage();await mobile.goto(`${baseURL}/en/timeline`,{waitUntil:"networkidle"});await scrollTimeline(mobile,.5);const mobileProgress=await style(mobile.locator(".timeline-list"),"::after");const mobileIndex=await closestEntry(mobile);const mobileDot=await style(mobile.locator(".timeline-dot").nth(mobileIndex));expect(mobileProgress.animationName).toBe("timeline-progress");expect(scaleY(mobileDot.scale)).toBeGreaterThan(1.2);const mobileViewport=await mobile.evaluate(()=>({clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth}));expect(mobileViewport.scrollWidth).toBe(mobileViewport.clientWidth);await mobile.screenshot({path:"artifacts/timeline-progress/mobile.png"});await mobileContext.close();

  const reducedContext=await browser.newContext({viewport:{width:390,height:844},reducedMotion:"reduce"});const reduced=await reducedContext.newPage();await reduced.goto(`${baseURL}/vi/timeline`,{waitUntil:"networkidle"});await scrollTimeline(reduced,.5);const reducedList=reduced.locator(".timeline-list");const reducedProgress=await style(reducedList,"::after");const reducedDot=await style(reduced.locator(".timeline-dot").nth(await closestEntry(reduced)));const reducedBase=await style(reducedList,"::before");expect(reducedProgress.animationName).toBe("none");expect(reducedProgress.opacity).toBe("0");expect(reducedProgress.scale).toBe("none");expect(reducedDot.animationName).toBe("none");expect(reducedDot.scale).toBe("none");expect(reducedBase.backgroundColor).not.toBe("rgba(0, 0, 0, 0)");await reduced.screenshot({path:"artifacts/timeline-progress/reduced-motion.png"});await reducedContext.close();

  const proof={generatedAt:new Date().toISOString(),url:new URL(baseURL).origin,desktop:{start,middle,end,activeIndex,activeDot,metrics,keyboardHref:href,axeCriticalOrSerious:0},mobile:{progress:mobileProgress,activeIndex:mobileIndex,activeDot:mobileDot,viewport:mobileViewport},reducedMotion:{progress:reducedProgress,dot:reducedDot,baseLine:reducedBase},screenshots:["artifacts/timeline-progress/desktop.png","artifacts/timeline-progress/mobile.png","artifacts/timeline-progress/reduced-motion.png"]};await writeFile("artifacts/timeline-progress/timeline-progress-proof.json",`${JSON.stringify(proof,null,2)}\n`);
});
