import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PublicShell } from "@/components/public/PublicShell";
import { isPublicLocale, t } from "@/lib/i18n/config";
import { getPublicClient } from "@/lib/public-client/client";
import { homePath, reconstructionPath } from "@/lib/public-client/paths";
export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale: raw } = await params; if (!isPublicLocale(raw)) return {}; return { title: raw === "vi" ? "Tái dựng lịch sử" : "Historical reconstructions", alternates: { canonical: reconstructionPath(raw), languages: { vi: reconstructionPath("vi"), en: reconstructionPath("en") } } }; }
export default async function ReconstructionIndex({ params }: { params: Promise<{ locale: string }> }) { const { locale: raw } = await params; if (!isPublicLocale(raw)) notFound(); const list = await getPublicClient().reconstructions(raw); const other = raw === "vi" ? "en" : "vi"; return <PublicShell locale={raw} localeHref={reconstructionPath(other)}><main id="noi-dung" className="listing-main reconstruction-main"><nav className="breadcrumbs" aria-label={raw === "vi" ? "Đường dẫn" : "Breadcrumb"}><Link href={homePath(raw)}>{t(raw).home}</Link><span>/</span><span aria-current="page">{raw === "vi" ? "Tái dựng" : "Reconstructions"}</span></nav><header className="listing-header"><p className="eyebrow">{raw === "vi" ? "Mô phỏng có nguồn" : "Sourced scenes"}</p><h1>{raw === "vi" ? "Tái dựng lịch sử để học cách đọc chứng cứ" : "Historical reconstructions for reading evidence"}</h1><p>{raw === "vi" ? "Mỗi scene là diễn giải giáo dục, có nguồn, giả định và độ tin cậy; narrative HTML luôn được ưu tiên." : "Each scene is an educational interpretation with sources, assumptions, and confidence; HTML narrative always comes first."}</p></header><div className="reconstruction-list">{list.data.map((item) => <article key={item.id}><span className="precision-chip">{item.confidence}</span><h2>{item.title}</h2><p>{item.summary}</p><Link className="text-link" href={reconstructionPath(raw, item.slug)}>{raw === "vi" ? "Mở tái dựng" : "Open reconstruction"}</Link></article>)}</div></main></PublicShell>; }
