import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PublicShell } from "@/components/public/PublicShell";
import { isPublicLocale, t } from "@/lib/i18n/config";
import { homePath } from "@/lib/public-client/paths";
export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; if (!isPublicLocale(locale)) return {}; return { title: locale === "vi" ? "Nguồn và kiểm chứng chương trình" : "Curriculum sources and verification" }; }
export default async function TransparencyPage({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; if (!isPublicLocale(locale)) notFound(); const vi = locale === "vi"; return <PublicShell locale={locale} localeHref={locale === "vi" ? "/en/nguon-va-kiem-chung" : "/vi/nguon-va-kiem-chung"}><main id="noi-dung" className="listing-main transparency-main"><nav className="breadcrumbs" aria-label={vi ? "Đường dẫn" : "Breadcrumb"}><Link href={homePath(locale)}>{t(locale).home}</Link><span>/</span><span aria-current="page">{vi ? "Nguồn và kiểm chứng" : "Sources and verification"}</span></nav><header className="listing-header"><p className="eyebrow">{vi ? "Báo cáo công khai" : "Public report"}</p><h1>{vi ? "Chương trình và bằng chứng kiểm chứng" : "Curriculum and verification evidence"}</h1><p>{vi ? "Báo cáo này đọc từ database phát hành và không tự thay đổi nội dung. Ô thiếu được giữ màu đỏ để đội biên tập tiếp tục nghiên cứu." : "This report reads the release database and never changes content. Missing cells stay red so editors can continue research."}</p></header><section className="transparency-callout"><strong>{vi ? "Trạng thái release" : "Release status"}</strong><span>{vi ? "Báo cáo máy được đính kèm ở artifacts/curriculum-completeness/curriculum-coverage.json." : "Machine report is attached at artifacts/curriculum-completeness/curriculum-coverage.json."}</span></section><section className="transparency-method"><h2>{vi ? "Quy tắc đọc" : "Reading rules"}</h2><ul><li>{vi ? "Mandatory yêu cầu lesson VI và EN, nguồn HTTPS, claim đã VERIFIED, reviewer và provenance." : "Mandatory requires VI and EN lessons, HTTPS sources, verified claims, a reviewer, and provenance."}</li><li>{vi ? "Elective được tách riêng, không cộng vào mandatory." : "Elective is separate and never counted toward mandatory."}</li><li>{vi ? "Không có nhãn ‘đầy đủ’ khi mọi ô bắt buộc chưa đạt." : "No ‘complete’ label appears until every mandatory cell passes."}</li></ul></section></main></PublicShell>; }
