import Link from "next/link";
import Image from "next/image";
import type { Locale, ReconstructionView } from "@/lib/content/types";
import { contentPath, reconstructionPath } from "@/lib/public-client/paths";
import { ReconstructionEnhancement } from "./ReconstructionEnhancement";

export function ReconstructionScene({ locale, scene }: { locale: Locale; scene: ReconstructionView }) {
  const vi = locale === "vi";
  return <div className="reconstruction-scene" data-testid="reconstruction-scene">
    <header className="reconstruction-header"><p className="eyebrow">{vi ? "Tái dựng giáo dục" : "Educational reconstruction"}</p><h1>{scene.title}</h1><p>{scene.summary}</p><div className="reconstruction-disclosure"><strong>{vi ? "Độ tin cậy tổng thể" : "Overall confidence"}: {scene.confidence}</strong><span>{vi ? "Đây là diễn giải có nguồn, không phải sự thật phục dựng tuyệt đối." : "A sourced interpretation, not an exact restoration of the past."}</span></div></header>
    <div className="reconstruction-grid" data-motion-context="reconstruction-phase">
      <section className="reconstruction-visual" aria-labelledby="scene-visual-title"><h2 id="scene-visual-title" className="sr-only">{vi ? "Sơ đồ diễn giải" : "Interpretive diagram"}</h2><div className="reconstruction-canvas" data-testid="reconstruction-canvas"><Image src={scene.fallback.image ?? "/images/reconstructions/bach-dang-1288-fallback.svg"} width={1200} height={520} priority alt={vi ? "Sơ đồ sông, bãi cọc và ba phase của tái dựng Bạch Đằng 1288" : "Diagram of the river, stake field, and three phases of the Bạch Đằng 1288 reconstruction"} /><ReconstructionEnhancement /></div><p className="reconstruction-fallback">{scene.fallback.narrative}</p></section>
      <section className="reconstruction-phases" aria-labelledby="phase-title"><div className="section-heading"><div><p className="eyebrow">{vi ? "Đọc theo trình tự" : "Read in sequence"}</p><h2 id="phase-title">{vi ? "Ba phase của câu chuyện" : "Three narrative phases"}</h2></div></div><ol>{scene.phases.map((phase) => <li key={phase.id} className="reconstruction-phase motion-phase-card"><button type="button" className="reconstruction-phase-button motion-context-link" data-motion-context="reconstruction-phase" aria-controls={`phase-${phase.id}`}><span>{phase.order}</span><strong>{phase.title}</strong><em>{phase.confidence}</em></button><div id={`phase-${phase.id}`} className="reconstruction-phase-body"><p className="phase-date">{phase.dateLabel}</p><p>{phase.narrative}</p><p className="phase-assumptions"><strong>{vi ? "Giả định" : "Assumptions"}:</strong> {phase.assumptions.join(" ")}</p><ul>{phase.moves.map((move) => <li key={move.id}><strong>{move.label}</strong> <span>({move.side}, {move.confidence})</span></li>)}</ul></div></li>)}</ol></section>
    </div>
    <section className="reconstruction-evidence" aria-labelledby="evidence-title"><h2 id="evidence-title">{vi ? "Nguồn và giới hạn" : "Sources and limits"}</h2><p>{scene.assumptions.join(" ")}</p><ul>{scene.sources.map((source) => <li key={source.id}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a><span>{source.sourceType} · {source.qualityTier}</span></li>)}</ul><p>{vi ? "Nội dung gốc" : "Source entry"}: <Link href={contentPath(locale, scene.content.type, scene.content.slug)}>{scene.content.title}</Link></p></section>
    <nav className="reconstruction-actions" aria-label={vi ? "Điều hướng tái dựng" : "Reconstruction navigation"}><Link className="button secondary" href={reconstructionPath(locale)}>{vi ? "Danh mục tái dựng" : "All reconstructions"}</Link></nav>
  </div>;
}
