"use client";

/* eslint-disable react-hooks/set-state-in-effect -- effects hydrate server-backed editor state */

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback,useEffect,useMemo,useState } from "react";
import { adminErrorMessage,adminGet,adminSend,data,fieldError } from "@/lib/admin-client/client";
import { canReview } from "@/lib/admin-client/navigation";
import type { AdminContentDetail,AdminMediaView,AdminSourceView,DataResponse,ListResponse,Locale } from "@/lib/admin-client/types";
import { useAdmin } from "./AdminShell";

const blankTranslation={title:"",slug:"",summary:"",body:"",seoTitle:"",seoDescription:"",translationStatus:"TRANSLATING" as const};
const kindPaths={vi:{EVENT:"su-kien",PERSON:"nhan-vat",ARTIFACT:"hien-vat",TOPIC:"chu-de",PERIOD:"thoi-ky"},en:{EVENT:"events",PERSON:"people",ARTIFACT:"artifacts",TOPIC:"topics",PERIOD:"periods"}};
const statusLabel={DRAFT:"Bản nháp",IN_REVIEW:"Chờ duyệt",REJECTED:"Đã trả lại",APPROVED:"Đã duyệt",PUBLISHED:"Đã xuất bản",ARCHIVED:"Đã lưu trữ"};

export function NewContentPage(){const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>();return <div className="admin-page"><header className="admin-page-header"><div><p className="eyebrow">Nội dung mới</p><h1>Tạo bản nháp tiếng Việt</h1><p>Năm trường chính tạo một đối tượng; SEO và metadata nằm trong “Tùy chọn thêm”.</p></div></header><form className="editor-card focused-form" onSubmit={async(event)=>{
  event.preventDefault();setBusy(true);setError(undefined);const form=new FormData(event.currentTarget);
  try{const title=String(form.get("title")||"");const summary=String(form.get("summary")||"");const response=await adminSend<DataResponse<AdminContentDetail>>("/api/v1/admin/contents","POST",{type:form.get("type"),sourceIds:[],translations:{vi:{title,slug:form.get("slug"),summary,body:form.get("body"),seoTitle:form.get("seoTitle")||title,seoDescription:form.get("seoDescription")||summary,translationStatus:"TRANSLATING"}}});const result=data(response);router.push(`/admin/contents/${result.id}`);}
  catch(next){setError(next);setBusy(false);}
}}>
  <label data-primary-field>Loại nội dung<select name="type" defaultValue="EVENT"><option value="EVENT">Sự kiện</option><option value="PERSON">Nhân vật</option><option value="ARTIFACT">Hiện vật</option><option value="TOPIC">Chủ đề</option><option value="PERIOD">Thời kỳ</option></select></label>
  <label data-primary-field>Tiêu đề<input name="title" required/>{fieldError(error,"title")?<small className="field-error">{fieldError(error,"title")}</small>:null}</label>
  <label data-primary-field>Slug<input name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="chien-dich-dien-bien-phu" required/>{fieldError(error,"slug")?<small className="field-error">{fieldError(error,"slug")}</small>:null}</label>
  <label data-primary-field>Tóm tắt<textarea name="summary" rows={3} required/></label>
  <label data-primary-field>Nội dung<textarea name="body" rows={8} required/></label>
  <details className="more-options"><summary>Tùy chọn thêm</summary><div><label>Tiêu đề SEO<input name="seoTitle"/></label><label>Mô tả SEO<textarea name="seoDescription" rows={2}/></label></div></details>
  {error?<p className="form-alert" role="alert">{adminErrorMessage(error)}</p>:null}<div className="form-actions"><Link className="button ghost" href="/admin/contents">Hủy</Link><button className="button primary" disabled={busy} type="submit">{busy?"Đang tạo…":"Tạo bản nháp"}</button></div></form></div>;}

export function ContentEditorPage({id}:{id:string}){const {user}=useAdmin();const [detail,setDetail]=useState<AdminContentDetail|null>(null);const [sources,setSources]=useState<AdminSourceView[]>([]);const [media,setMedia]=useState<AdminMediaView[]>([]);const [activeLocale,setActiveLocale]=useState<Locale>("vi");const [translation,setTranslation]=useState(blankTranslation);const [sourceIds,setSourceIds]=useState<string[]>([]);const [mediaIds,setMediaIds]=useState<string[]>([]);const [dirty,setDirty]=useState(false);const [error,setError]=useState<unknown>();const [notice,setNotice]=useState("");const [preview,setPreview]=useState(false);const [rejectReason,setRejectReason]=useState("");
  const load=useCallback(async()=>{try{const [content,sourceList,mediaList]=await Promise.all([adminGet<DataResponse<AdminContentDetail>>(`/api/v1/admin/contents/${id}`),adminGet<ListResponse<AdminSourceView>>("/api/v1/admin/sources?pageSize=100"),adminGet<ListResponse<AdminMediaView>>("/api/v1/admin/media?pageSize=100")]);const next=data(content);setDetail(next);setSources(sourceList.data);setMedia(mediaList.data);setSourceIds(next.sourceIds);setMediaIds(next.mediaIds);setError(undefined);setDirty(false);}catch(next){setError(next);}},[id]);
  useEffect(()=>{void load();},[load]);useEffect(()=>{if(!detail)return;const value=detail.translations[activeLocale];setTranslation(value?{title:value.title,slug:value.slug,summary:value.summary,body:value.body,seoTitle:value.seoTitle,seoDescription:value.seoDescription,translationStatus:"TRANSLATING" as const}:blankTranslation);setDirty(false);},[activeLocale,detail]);useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue="";}};const guard=(event:MouseEvent)=>{if(!dirty||!(event.target instanceof Element))return;const link=event.target.closest("a[href]");const href=link?.getAttribute("href");if(href&&!href.startsWith("#")&&!window.confirm("Bỏ các thay đổi chưa lưu?")){event.preventDefault();event.stopPropagation();}};window.addEventListener("beforeunload",warn);document.addEventListener("click",guard,true);return()=>{window.removeEventListener("beforeunload",warn);document.removeEventListener("click",guard,true);};},[dirty]);
  const locales=useMemo(()=>detail?(Object.keys(detail.translations) as Locale[]):[],[detail]);
  const submitLocales=locales.filter((locale)=>detail?.translations[locale]?.translationStatus==="TRANSLATING");
  const reviewLocales=locales.filter((locale)=>detail?.translations[locale]?.translationStatus==="READY_FOR_REVIEW");
  const publishLocales=locales.filter((locale)=>detail?.translations[locale]?.translationStatus==="APPROVED");
  const update=(name:keyof typeof blankTranslation,value:string)=>{setTranslation((current)=>({...current,[name]:value}));setDirty(true);};
  const mutate=async(path:string,method:"POST"|"PATCH"|"PUT",body:unknown,success:string)=>{try{setError(undefined);await adminSend(path,method,body);setNotice(success);await load();}catch(next){setError(next);setNotice("");}};
  if(!detail)return <div className="admin-page"><p aria-live="polite">{error?adminErrorMessage(error):"Đang tải nội dung…"}</p></div>;
  const existing=detail.translations[activeLocale];const publicTranslation=detail.translations.vi||detail.translations.en;const publicLocale=detail.translations.vi?"vi":"en";const publicHref=publicTranslation?`/${publicLocale}/${kindPaths[publicLocale][detail.type]}/${publicTranslation.slug}`:"";
  return <div className="admin-page editor-page"><div className="admin-editor-top"><nav className="admin-breadcrumb" aria-label="Đường dẫn biên tập"><Link href="/admin/contents">Nội dung</Link><span>/</span><span>{detail.titles.vi||detail.titles.en||"Bản nháp"}</span></nav><button className="button secondary" type="button" onClick={()=>setPreview(true)}>Xem trước</button></div>
    <header className="object-header"><div><span className={`status-chip status-${detail.status.toLowerCase()}`}>{statusLabel[detail.status]}</span><h1>{detail.titles.vi||detail.titles.en||"Nội dung chưa đặt tên"}</h1><p>Lần cập nhật {detail.version} · bởi {detail.updatedBy}</p></div><button className="button primary" type="button" disabled={!submitLocales.length} onClick={()=>void mutate(`/api/v1/admin/contents/${id}/submit-review`,"POST",{version:detail.version,locales:submitLocales},"Đã gửi nội dung tới danh sách chờ duyệt.")}>Gửi duyệt</button></header>
    <section className="object-pulse" aria-label="Tình trạng nội dung"><span><strong>{locales.length}/2</strong> ngôn ngữ</span><span><strong>{detail.sourceIds.length}</strong> nguồn</span><span><strong>{detail.mediaIds.length}</strong> media</span><span><strong>{statusLabel[detail.status]}</strong> kiểm duyệt</span></section>
    {notice?<p className="success-alert" role="status">{notice}{detail.status==="PUBLISHED"&&publicHref?<> <Link href={publicHref}>Mở trang công khai</Link></>:null}</p>:null}{error?<p className="form-alert" role="alert">{adminErrorMessage(error)}</p>:null}
    <section className="editor-card"><div className="form-heading"><div><h2>Thông tin hiển thị</h2><p>Hai ngôn ngữ là hai bản của cùng một nội dung lịch sử.</p></div><div className="locale-tabs" role="tablist" aria-label="Ngôn ngữ nội dung">{(["vi","en"] as Locale[]).map((locale)=><button className={activeLocale===locale?"active":""} type="button" role="tab" aria-selected={activeLocale===locale} key={locale} onClick={()=>{if(!dirty||window.confirm("Bỏ các thay đổi chưa lưu?"))setActiveLocale(locale);}}>{locale==="vi"?"Tiếng Việt":"English"}</button>)}</div></div>
      <form className="translation-form" onSubmit={async(event)=>{event.preventDefault();await mutate(`/api/v1/admin/contents/${id}/translations/${activeLocale}`,"PUT",{version:existing?.version??0,...translation,seoTitle:translation.seoTitle||translation.title,seoDescription:translation.seoDescription||translation.summary,translationStatus:"TRANSLATING"},`Đã lưu bản ${activeLocale.toUpperCase()}.`);}}>
        <label data-primary-field>{activeLocale==="vi"?"Tiêu đề":"Title"}<input value={translation.title} onChange={(event)=>update("title",event.target.value)} required/>{fieldError(error,"title")?<small className="field-error">{fieldError(error,"title")}</small>:null}</label>
        <label data-primary-field>Slug<input value={translation.slug} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" onChange={(event)=>update("slug",event.target.value)} required/></label>
        <label data-primary-field>{activeLocale==="vi"?"Tóm tắt":"Summary"}<textarea rows={3} value={translation.summary} onChange={(event)=>update("summary",event.target.value)} required/></label>
        <label data-primary-field>{activeLocale==="vi"?"Nội dung":"Body"}<textarea rows={9} value={translation.body} onChange={(event)=>update("body",event.target.value)} required/></label>
        <details className="more-options"><summary>Tùy chọn thêm</summary><div><label>Tiêu đề SEO<input value={translation.seoTitle} onChange={(event)=>update("seoTitle",event.target.value)}/></label><label>Mô tả SEO<textarea rows={3} value={translation.seoDescription} onChange={(event)=>update("seoDescription",event.target.value)}/></label></div></details>
        <div className="inline-save"><span>{dirty?"Thay đổi chưa lưu":"Đã đồng bộ"}</span><button className="button primary" type="submit">Lưu bản {activeLocale.toUpperCase()}</button></div>
      </form>
    </section>
    <section className="editor-card"><div className="form-heading"><div><h2>Metadata đối tượng</h2><p>Ngày tháng và ngữ cảnh dùng chung cho cả hai ngôn ngữ.</p></div></div><form className="metadata-form" key={detail.version} onSubmit={async(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);await mutate(`/api/v1/admin/contents/${id}`,"PATCH",{version:detail.version,featured:form.get("featured")==="on",startDate:form.get("startDate")||undefined,endDate:form.get("endDate")||undefined,datePrecision:form.get("datePrecision")||undefined,location:form.get("location")||undefined,result:form.get("result")||undefined,role:form.get("role")||undefined},"Đã lưu metadata.");}}><label>Ngày bắt đầu<input name="startDate" type="date" defaultValue={detail.startDate??""}/></label><label>Ngày kết thúc<input name="endDate" type="date" defaultValue={detail.endDate??""}/></label><label>Độ chính xác<select name="datePrecision" defaultValue={detail.datePrecision??""}><option value="">Chưa đặt</option><option value="DAY">Đủ ngày</option><option value="MONTH">Chỉ biết tháng</option><option value="YEAR">Chỉ biết năm</option><option value="APPROXIMATE">Ước lệ</option></select></label><label>Địa điểm<input name="location" defaultValue={detail.location??""}/></label><label>Kết quả<textarea name="result" rows={2} defaultValue={detail.result??""}/></label><label>Vai trò<input name="role" defaultValue={detail.role??""}/></label><label className="check-label"><input name="featured" type="checkbox" defaultChecked={detail.featured}/> Nội dung nổi bật</label><button className="button secondary" type="submit">Lưu metadata</button></form></section>
    <section className="editor-card"><div className="form-heading"><div><h2>Nguồn và media</h2><p>Chọn metadata đã có hoặc tạo mới ngay trên cùng đối tượng.</p></div></div><div className="attachment-columns"><div><h3>Nguồn tư liệu</h3>{sources.map((source)=><label className="attachment-row" key={source.id}><input type="checkbox" checked={sourceIds.includes(source.id)} onChange={(event)=>{setSourceIds((current)=>event.target.checked?[...current,source.id]:current.filter((value)=>value!==source.id));setDirty(true);}}/><span><strong>{source.title}</strong><small>{source.publisher||source.url}</small></span></label>)}<details className="more-options"><summary>+ Thêm nguồn</summary><form className="mini-form" onSubmit={async(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);try{const created=data(await adminSend<DataResponse<AdminSourceView>>("/api/v1/admin/sources","POST",{title:form.get("title"),url:form.get("url"),accessedAt:new Date(String(form.get("accessedAt"))).toISOString()}));await adminSend(`/api/v1/admin/contents/${id}`,"PATCH",{version:detail.version,sourceIds:[...detail.sourceIds,created.id]});setNotice("Đã tạo và gắn nguồn.");await load();}catch(next){setError(next);}}}><label>Tiêu đề<input name="title" required/></label><label>URL HTTPS<input name="url" type="url" pattern="https://.*" required/></label><label>Ngày truy cập<input name="accessedAt" type="datetime-local" required/></label><button className="button secondary" type="submit">Tạo và gắn nguồn</button></form></details></div>
      <div><h3>Media</h3>{media.map((item)=><label className="attachment-row" key={item.id}><input type="checkbox" checked={mediaIds.includes(item.id)} onChange={(event)=>{setMediaIds((current)=>event.target.checked?[...current,item.id]:current.filter((value)=>value!==item.id));setDirty(true);}}/><span><strong>{item.credit}</strong><small>{item.kind} · {item.license}</small></span></label>)}<details className="more-options"><summary>+ Thêm media</summary><form className="mini-form" onSubmit={async(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);try{const created=data(await adminSend<DataResponse<AdminMediaView>>("/api/v1/admin/media","POST",{url:form.get("url"),kind:form.get("kind"),credit:form.get("credit"),license:form.get("license"),altVi:form.get("altVi"),altEn:form.get("altEn")}));await adminSend(`/api/v1/admin/contents/${id}`,"PATCH",{version:detail.version,mediaIds:[...detail.mediaIds,created.id]});setNotice("Đã tạo và gắn media.");await load();}catch(next){setError(next);}}}><label>URL HTTPS<input name="url" type="url" pattern="https://.*" required/></label><label>Loại<select name="kind"><option value="IMAGE">Hình ảnh</option><option value="DOCUMENT">Tài liệu</option></select></label><label>Ghi công<input name="credit" required/></label><label>Giấy phép<input name="license" required/></label><label>Alt VI<input name="altVi" required/></label><label>Alt EN<input name="altEn" required/></label><button className="button secondary" type="submit">Tạo và gắn media</button></form></details></div></div><button className="button secondary" type="button" onClick={()=>void mutate(`/api/v1/admin/contents/${id}`,"PATCH",{version:detail.version,sourceIds,mediaIds},"Đã lưu nguồn và media.")}>Lưu lựa chọn</button></section>
    {canReview(user.role)?<section className="review-panel"><div><p className="eyebrow">Góc nhìn người duyệt</p><h2>Kiểm tra trước khi xuất bản</h2><ul className="review-checks"><li className={locales.length?"complete":"blocked"}>Bản ngôn ngữ đã lưu</li><li className={detail.sourceIds.length?"complete":"blocked"}>Có ít nhất một nguồn</li><li className="complete">Media đã khai báo credit, license và alt</li></ul></div><div className="review-actions-panel"><label>Lý do trả lại<textarea rows={3} value={rejectReason} onChange={(event)=>setRejectReason(event.target.value)} placeholder="Nêu rõ nội dung cần chỉnh sửa"/></label><div><button className="button secondary" type="button" disabled={!rejectReason.trim()||!reviewLocales.length} onClick={()=>void mutate(`/api/v1/admin/contents/${id}/reject`,"POST",{version:detail.version,locales:reviewLocales,reason:rejectReason},"Đã trả nội dung cho Editor.")}>Trả lại</button><button className="button primary" type="button" disabled={!reviewLocales.length} onClick={()=>void mutate(`/api/v1/admin/contents/${id}/approve`,"POST",{version:detail.version,locales:reviewLocales},"Đã duyệt nội dung.")}>Duyệt nội dung</button><button className="button primary" type="button" disabled={!publishLocales.length} onClick={()=>void mutate(`/api/v1/admin/contents/${id}/publish`,"POST",{version:detail.version,locales:publishLocales},"Đã xuất bản nội dung.")}>Xuất bản</button></div></div></section>:null}
    {preview?<div className="dialog-backdrop" role="presentation" onMouseDown={()=>setPreview(false)}><section className="preview-dialog" role="dialog" aria-modal="true" aria-labelledby="preview-title" onMouseDown={(event)=>event.stopPropagation()}><button className="dialog-close" type="button" onClick={()=>setPreview(false)}>Đóng</button><p className="eyebrow">Xem trước {activeLocale.toUpperCase()}</p><h2 id="preview-title">{translation.title||"Chưa có tiêu đề"}</h2><p className="preview-summary">{translation.summary}</p><div className="preview-body">{translation.body}</div></section></div>:null}
  </div>;
}
