"use client";
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import { adminErrorMessage,adminGet,list } from "@/lib/admin-client/client";
import type { ListResponse,PublishedHistoryQueueItem } from "@/lib/admin-client/types";
import { useAdmin } from "./AdminShell";
const date=(value:string|null)=>value?new Intl.DateTimeFormat("vi-VN",{dateStyle:"medium"}).format(new Date(value)):"—";
const evidenceLabel=(value:"READY"|"MISSING_OR_UNVERIFIED")=>value==="READY"?"Đã có locator kiểm chứng":"Cần bổ sung hoặc kiểm chứng";
const translationLabel=(value:string|null|undefined)=>value?({PUBLISHED:"Đã xuất bản",APPROVED:"Đã duyệt",READY_FOR_REVIEW:"Sẵn sàng duyệt",TRANSLATING:"Đang biên tập",NOT_STARTED:"Chưa bắt đầu"}[value]??value):"Chưa có";
export function PublishedHistoryQueue(){const{user}=useAdmin();const[items,setItems]=useState<PublishedHistoryQueueItem[]>([]);const[meta,setMeta]=useState({page:1,pageSize:25,total:0,totalPages:0});const[message,setMessage]=useState("");const load=useCallback(async(page=meta.page)=>{try{const response=await adminGet<ListResponse<PublishedHistoryQueueItem>>(`/api/v1/admin/published-history?page=${page}&pageSize=${meta.pageSize}`);setItems(list(response));setMeta(response.meta);setMessage("");}catch(error){setMessage(adminErrorMessage(error));}},[meta.page,meta.pageSize]);useEffect(()=>{if(user.role!=="ADMIN"&&user.role!=="REVIEWER")return;const timer=window.setTimeout(()=>{void load();},0);return()=>window.clearTimeout(timer);},[load,user.role]);if(user.role!=="ADMIN"&&user.role!=="REVIEWER")return <div className="admin-page"><h1>Không có quyền</h1></div>;return <div className="admin-page"><header className="admin-page-header"><div><p className="eyebrow">Danh sách kiểm duyệt</p><h1>Lịch sử cần xác nhận</h1><p>{meta.total} nội dung đã xuất bản đang chờ người có quyền đối chiếu lịch sử biên tập. Mở từng mục để xác nhận bằng locator nguồn và ghi chú.</p></div></header>{message?<p className="form-alert" role="alert">{message}</p>:null}<div className="admin-table" role="table" aria-label="Nội dung thiếu lịch sử biên tập">{items.map(item=><div role="row" key={item.id}><span role="cell"><strong>{item.titles.vi||item.titles.en||item.id}</strong><small>{item.type} · version {item.version}</small><small>Nguồn: {evidenceLabel(item.sourceLocatorStatus)} · Luận điểm: {evidenceLabel(item.claimLocatorStatus)}</small><small>VI: {translationLabel(item.translationStatuses.vi)} · EN: {translationLabel(item.translationStatuses.en)}</small></span><span role="cell">Xuất bản {date(item.publishedAt)}</span><span role="cell"><Link className="button secondary" href={`/admin/contents/${item.id}`}>Mở nội dung</Link></span></div>)}</div><div className="form-actions"><button className="button secondary" disabled={meta.page<=1} onClick={()=>void load(meta.page-1)}>Trang trước</button><span>Trang {meta.page}/{Math.max(1,meta.totalPages)}</span><button className="button secondary" disabled={meta.page>=meta.totalPages} onClick={()=>void load(meta.page+1)}>Trang sau</button></div></div>}
