import Database from "better-sqlite3";
import { afterAll,beforeEach,describe,expect,it } from "vitest";
import { copyFileSync,mkdtempSync,rmSync } from "node:fs";
import { join,resolve } from "node:path";
import { tmpdir } from "node:os";
import { GET as queueRoute } from "@/app/api/v1/admin/published-history/route";
import { POST as loginRoute } from "@/app/api/v1/auth/login/route";
const origin="https://history-queue.quansuviet.test";const directory=mkdtempSync(join(tmpdir(),"qsv-history-queue-"));const databasePath=join(directory,"queue.db");
function request(method:string,path:string,body?:unknown,cookie?:string){const headers=new Headers({Origin:origin});if(body!==undefined)headers.set("Content-Type","application/json");if(cookie)headers.set("Cookie",cookie);return new Request(`${origin}${path}`,{method,headers,...(body===undefined?{}:{body:JSON.stringify(body)})});}
async function login(email:string,password:string){const response=await loginRoute(request("POST","/api/v1/auth/login",{email,password}));expect(response.status).toBe(200);return response.headers.get("set-cookie")!.split(";",1)[0];}
 describe("published history queue",()=>{beforeEach(()=>{process.env.DATABASE_PATH=databasePath;process.env.APP_ORIGIN=origin;process.env.SESSION_SECRET="history-queue-test-session-secret-at-least-32";rmSync(databasePath,{force:true});copyFileSync(resolve("data/quan-su-viet.db"),databasePath);});afterAll(()=>{delete process.env.DATABASE_PATH;rmSync(directory,{recursive:true,force:true});});it("is paginated, reviewer-only, evidence-aware, and read-only",async()=>{const reviewer=await login("reviewer@quansuviet.local","Reviewer-Demo-2026!");const response=await queueRoute(request("GET","/api/v1/admin/published-history?pageSize=25",undefined,reviewer));expect(response.status).toBe(200);const payload=await response.json();expect(payload).toMatchObject({meta:{total:105,pageSize:25,totalPages:5}});expect(payload.data).toHaveLength(25);expect(payload.data.every((row:{status:string;translationStatuses:Record<string,string|null>;sourceLocatorStatus:string;claimLocatorStatus:string})=>row.status==="PUBLISHED"&&["READY","MISSING_OR_UNVERIFIED"].includes(row.sourceLocatorStatus)&&["READY","MISSING_OR_UNVERIFIED"].includes(row.claimLocatorStatus)&&Object.hasOwn(row.translationStatuses,"vi")&&Object.hasOwn(row.translationStatuses,"en"))).toBe(true);const editor=await login("editor@quansuviet.local","Editor-Demo-2026!");expect((await queueRoute(request("GET","/api/v1/admin/published-history",undefined,editor))).status).toBe(403);const database=new Database(databasePath,{readonly:true});try{expect(database.prepare("SELECT COUNT(*) AS count FROM audit_logs WHERE action LIKE 'content.editorial_history.%'").get()).toEqual({count:0});}finally{database.close();}});});
