"use client";
import { useState } from "react";
import type { AiAnswer } from "@/lib/ai/contract";

export function ContextualTutor({ locale, lessonTitle }: { locale: "vi" | "en"; lessonTitle: string }) {
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState<AiAnswer | null>(null);
  const [message, setMessage] = useState("");
  const prompts = locale === "vi" ? ["Giải thích bài học này ngắn gọn.", "Luận điểm nào có nguồn để tôi kiểm chứng?", "Tôi nên đặt câu hỏi nào tiếp theo?"] : ["Explain this lesson briefly.", "Which claim can I verify from a source?", "What should I ask next?"];
  async function ask(value = question) { setMessage(""); const response = await fetch(`/api/v1/${locale}/ai/answer`, { method: "POST", headers: { "content-type": "application/json", "x-qsv-ai-alpha": "internal" }, body: JSON.stringify({ question: value, alpha: true }) }); const payload = await response.json(); if (!response.ok) { setMessage(payload.message || "AI is disabled"); setAnswer(null); return; } setAnswer(payload.data); }
  return <aside className="contextual-tutor" aria-labelledby="contextual-tutor-title"><div className="contextual-tutor-header"><p className="eyebrow">{locale === "vi" ? "Internal alpha" : "Internal alpha"}</p><h2 id="contextual-tutor-title">{locale === "vi" ? "Trợ giảng theo ngữ cảnh" : "Contextual tutor"}</h2><p>{locale === "vi" ? `Đang thử nghiệm bên cạnh bài: ${lessonTitle}. Không phải Public Beta; câu trả lời luôn cần nguồn.` : `Testing beside: ${lessonTitle}. Not Public Beta; answers require sources.`}</p></div><div className="contextual-tutor-prompts">{prompts.map((prompt) => <button className="button secondary" type="button" key={prompt} onClick={() => { setQuestion(prompt); void ask(prompt); }}>{prompt}</button>)}</div><form onSubmit={(event) => { event.preventDefault(); void ask(); }}><label>{locale === "vi" ? "Câu hỏi trong bài" : "Question about this lesson"}<textarea value={question} onChange={(event) => setQuestion(event.target.value)} rows={3} /></label><button className="button primary" type="submit">{locale === "vi" ? "Hỏi trong alpha" : "Ask alpha"}</button></form>{message ? <p className="form-message" role="alert">{message}</p> : null}{answer ? <div className="contextual-tutor-answer" aria-live="polite"><strong>{answer.status === "GROUNDED" ? (locale === "vi" ? "Có nguồn hỗ trợ" : "Grounded") : (locale === "vi" ? "Chưa đủ nguồn" : "Not enough evidence")}</strong><p>{answer.answer}</p>{answer.citations.length ? <ol>{answer.citations.map((citation) => <li key={citation.sourceId}><a href={citation.url} target="_blank" rel="noreferrer">{citation.title}</a><span>{citation.locator}</span></li>)}</ol> : null}</div> : null}</aside>;
}
