import type { ReactNode } from "react";

type Dashboard = { releaseStatus: string; coverage: { mandatory: unknown }; rights: { status: string; servedBinary: number; linkOnly: number }; ai: { status: string; targetQuestions: number; actualQuestions: number; targetGap: number; citationPrecision?: number; injectionLeakRate?: number; publicBeta: boolean }; privacy: { status: string; publicAi: string }; corrections: { lastIntake: string; slaHours: number | null; reporterPublic: boolean }; operations: { readiness: string; fixedProductionDomain: boolean; backupRestoreVerified: boolean }; wikimedia?: { metadataRecords: number; rightsStatus: string; reviewStatus: string; binaryDownloaded: boolean }; aiComparison?: { status: string; configs: string[]; modelIndependence: string; humanApproval: string }; blockers: string[]; disclosure: string };

export function TransparencyDashboard({ locale, dashboard }: { locale: "vi" | "en"; dashboard: Dashboard }) {
  const vi = locale === "vi";
  const metric = (label: string, value: ReactNode, detail?: ReactNode) => <div className="transparency-metric"><span>{label}</span><strong>{value}</strong>{detail ? <small>{detail}</small> : null}</div>;
  return <div className="transparency-dashboard"><section className="transparency-status" aria-labelledby="transparency-status-title"><p className="eyebrow">{vi ? "Báo cáo công khai" : "Public report"}</p><h1 id="transparency-status-title">{vi ? "Minh bạch về phạm vi, nguồn và AI" : "Transparency about scope, sources, and AI"}</h1><p>{vi ? "Trang này đọc bằng chứng triển khai và giữ nguyên các blocker. Nó không phải là sự chứng thực của một Hội đồng sử học độc lập." : "This page reports implementation evidence and keeps blockers visible. It is not an independent historian council endorsement."}</p><div className="transparency-release"><span>{vi ? "Trạng thái release" : "Release status"}</span><strong>{dashboard.releaseStatus}</strong></div></section><section className="transparency-grid" aria-label={vi ? "Chỉ số minh bạch" : "Transparency metrics"}>{metric(vi ? "Mandatory coverage" : "Mandatory coverage", String(dashboard.coverage.mandatory))}{metric(vi ? "Media được phục vụ" : "Binary served", dashboard.rights.servedBinary, `${vi ? "LINK_ONLY" : "LINK_ONLY"}: ${dashboard.rights.linkOnly}`)}{metric(vi ? "AI eval" : "AI eval", `${dashboard.ai.actualQuestions}/${dashboard.ai.targetQuestions}`, `${vi ? "Còn thiếu" : "Gap"}: ${dashboard.ai.targetGap}`)}{metric(vi ? "AI public beta" : "Public AI beta", dashboard.ai.publicBeta ? "ENABLED" : "DISABLED", dashboard.ai.status)}{metric(vi ? "Wikimedia metadata" : "Wikimedia metadata", dashboard.wikimedia?.metadataRecords ?? "—", dashboard.wikimedia ? `${dashboard.wikimedia.rightsStatus} · ${dashboard.wikimedia.reviewStatus}` : undefined)}{metric(vi ? "AI config" : "AI config", dashboard.aiComparison?.status ?? "—", dashboard.aiComparison?.humanApproval)}{metric(vi ? "Privacy" : "Privacy", dashboard.privacy.status, dashboard.privacy.publicAi)}{metric(vi ? "Correction SLA" : "Correction SLA", dashboard.corrections.slaHours ? `${dashboard.corrections.slaHours}h` : "—", dashboard.corrections.reporterPublic ? "public reporter data" : "reporter private")}{metric(vi ? "Operations" : "Operations", dashboard.operations.readiness, dashboard.operations.fixedProductionDomain ? "fixed domain" : "no fixed domain")}</section><section className="transparency-blockers" aria-labelledby="transparency-blockers-title"><h2 id="transparency-blockers-title">{vi ? "Blocker trước Public Beta" : "Public Beta blockers"}</h2><ul>{dashboard.blockers.map((blocker) => <li key={blocker}>{blocker}</li>)}</ul></section><p className="transparency-disclosure">{dashboard.disclosure}</p></div>;
}
