import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import Database from "better-sqlite3";

const args = process.argv.slice(2);
const option = (name, fallback) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : fallback; };
const databasePath = resolve(option("--database", process.env.DATABASE_PATH || "data/quan-su-viet.db"));
const output = resolve(option("--output", "artifacts/approved-corpus/snapshot.json"));
const requestedContentId = option("--content-id", null);
const requestedPrefix = option("--content-prefix", "lesson-");
const startedAt = new Date().toISOString();
const fail = (error) => { const report = { generatedAt: startedAt, database: databasePath, status: "FAIL", error: String(error), remediation: "Review/publish the missing evidence; this command never mutates the database." }; mkdirSync(dirname(output), { recursive: true }); writeFileSync(output, `${JSON.stringify(report, null, 2)}\n`); writeFileSync(output.replace(/\.json$/, ".md"), `# Approved corpus failure\n\n- Status: **FAIL**\n- Error: ${report.error}\n- Database mutation: **NO**\n`); process.stderr.write(`${JSON.stringify(report)}\n`); process.exitCode = 1; };
if (!existsSync(databasePath)) { fail(new Error("Database file does not exist")); } else {
  const database = new Database(databasePath, { readonly: true, fileMustExist: true });
  try {
    const rows = database.prepare(`SELECT n.id,n.type,t.locale,t.title,t.slug,t.summary,t.body,t.updated_at AS updatedAt FROM content_nodes n JOIN content_translations t ON t.node_id=n.id WHERE n.status='PUBLISHED' AND t.translation_status='PUBLISHED' AND ((? IS NOT NULL AND n.id=?) OR (? IS NULL AND n.id LIKE ? || '%')) ORDER BY n.id,t.locale`).all(requestedContentId, requestedContentId, requestedContentId, requestedPrefix);
    const sourceRows = database.prepare(`SELECT cs.content_id AS contentId,s.id,s.title,s.url,s.verification_status AS verificationStatus,s.source_type AS sourceType,s.quality_tier AS qualityTier,s.accessed_at AS accessedAt,s.institution,s.identifier,s.checksum FROM content_sources cs JOIN sources s ON s.id=cs.source_id WHERE ((? IS NOT NULL AND cs.content_id=?) OR (? IS NULL AND cs.content_id LIKE ? || '%')) ORDER BY cs.content_id,s.id`).all(requestedContentId, requestedContentId, requestedContentId, requestedPrefix);
    const claims = database.prepare(`SELECT c.id,c.content_id AS contentId,c.claim_type AS claimType,c.assessment,c.statement_vi AS statementVi,c.statement_en AS statementEn,c.verification_status AS verificationStatus,ce.source_id AS sourceId,ce.locator,ce.note FROM content_claims c JOIN claim_evidence ce ON ce.claim_id=c.id WHERE c.verification_status='VERIFIED' AND ((? IS NOT NULL AND c.content_id=?) OR (? IS NULL AND c.content_id LIKE ? || '%')) ORDER BY c.id,ce.source_id`).all(requestedContentId, requestedContentId, requestedContentId, requestedPrefix);
    const byContent = new Map(); for (const row of sourceRows) (byContent.get(row.contentId) || byContent.set(row.contentId, []).get(row.contentId)).push(row);
    const claimByContent = new Map(); for (const row of claims) (claimByContent.get(row.contentId) || claimByContent.set(row.contentId, []).get(row.contentId)).push(row);
    const violations = []; const approved = [];
    for (const row of rows) { const sources = byContent.get(row.id) || []; const contentClaims = claimByContent.get(row.id) || []; if (!sources.length || sources.some((s) => s.verificationStatus !== "VERIFIED" || !s.url || !s.accessedAt)) violations.push({ contentId: row.id, reason: "missing verified provenance" }); if (!contentClaims.length || contentClaims.some((c) => c.verificationStatus !== "VERIFIED" || !c.locator)) violations.push({ contentId: row.id, reason: "missing verified claim evidence" }); approved.push({ ...row, sources, claims: contentClaims }); }
    if (requestedContentId && !rows.length) { const target = database.prepare("SELECT id,status FROM content_nodes WHERE id=?").get(requestedContentId); if (!target) throw new Error(`Content not found: ${requestedContentId}`); rows.push({ id: target.id, type: "UNKNOWN", locale: "—", title: "", slug: "", summary: "", body: "", updatedAt: null }); }
    if (violations.length) throw new Error(JSON.stringify({ code: "CORPUS_NOT_APPROVED", violations }));
    const canonical = JSON.stringify(approved); const sha256 = createHash("sha256").update(canonical).digest("hex"); const tokens = new Map(); for (const row of approved) { for (const word of `${row.title} ${row.summary} ${row.body}`.toLocaleLowerCase("vi").match(/[\p{L}\p{N}]{3,}/gu) || []) { const list = tokens.get(word) || []; if (!list.includes(row.id)) list.push(row.id); tokens.set(word, list); } }
    const index = Object.fromEntries([...tokens.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([token, ids]) => [token, ids])); const report = { generatedAt: startedAt, database: databasePath, status: "PASS", snapshotVersion: "approved-corpus-v1", scope: requestedContentId ? { contentId: requestedContentId } : { rule: "PUBLISHED translations with verified claims/evidence" }, schemaVersion: database.prepare("SELECT MAX(version) AS version FROM schema_migrations").get().version, sha256, counts: { translations: approved.length, content: new Set(approved.map((r) => r.id)).size, sources: new Set(sourceRows.map((r) => r.id)).size, claims: new Set(claims.map((r) => r.id)).size, indexTerms: Object.keys(index).length }, records: approved, index };
    mkdirSync(dirname(output), { recursive: true }); writeFileSync(output, `${JSON.stringify(report, null, 2)}\n`); writeFileSync(output.replace(/\.json$/, ".md"), `# Approved corpus snapshot\n\n- Status: **PASS**\n- SHA-256: \`${sha256}\`\n- Translations: ${report.counts.translations}\n- Content: ${report.counts.content}\n- Verified sources: ${report.counts.sources}\n- Verified claims: ${report.counts.claims}\n- Index terms: ${report.counts.indexTerms}\n- Database mutation: **NO**\n`); process.stdout.write(`${JSON.stringify({ ...report, records: undefined, index: undefined })}\n`);
  } catch (error) { fail(error); } finally { database.close(); }
}
