import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PublicShell } from "@/components/public/PublicShell";
import { ContentCard } from "@/components/public/ContentCard";
import { CopyLinkButton } from "@/components/public/CopyLinkButton";
import { JsonLd } from "@/components/public/JsonLd";
import { BookIcon } from "@/components/icons";
import { isPublicLocale,t } from "@/lib/i18n/config";
import { contentArtwork } from "@/lib/public-client/artwork";
import { getPublicClient,PublicClientError } from "@/lib/public-client/client";
import { absolutePublicUrl,alternateApiToPublicPath,contentCollectionPath,contentPath,contentTypeFromLocaleSegment,homePath } from "@/lib/public-client/paths";
import { formatDateRange,formatIsoDate,typeLabel } from "@/lib/public-client/presentation";
import type { ContentDetail,ContentType,Locale } from "@/lib/content/types";
import { ContextualTutor } from "@/components/public/ContextualTutor";

export const dynamic="force-dynamic";
type Params={locale:string;kind:string;slug:string};
async function load(params:Params):Promise<{locale:Locale;type:ContentType;detail:ContentDetail}>{if(!isPublicLocale(params.locale))notFound();const type=contentTypeFromLocaleSegment(params.locale,params.kind);if(!type)notFound();try{return{locale:params.locale,type,detail:await getPublicClient().detail(params.locale,type,params.slug)};}catch(error){if(error instanceof PublicClientError&&error.status===404)notFound();throw error;}}

export async function generateMetadata({params}:{params:Promise<Params>}):Promise<Metadata>{const loaded=await load(await params);const {locale,type,detail}=loaded;const canonical=contentPath(locale,type,detail.slug);const alternate=detail.alternate?alternateApiToPublicPath(detail.alternate.url):null;const languages:Record<string,string>={[locale]:canonical};if(alternate)languages[detail.alternate!.locale]=alternate;const media=detail.media.find((item)=>/\.(?:avif|jpe?g|png|webp)(?:\?|$)/i.test(item.url));const artwork=contentArtwork(detail.id,locale);return{title:detail.title,description:detail.summary,alternates:{canonical,languages},openGraph:{title:detail.title,description:detail.summary,url:canonical,type:"article",publishedTime:detail.publishedAt,modifiedTime:detail.updatedAt,locale:locale==="vi"?"vi_VN":"en_GB",images:media?[{url:media.url,alt:media.alt}]:artwork?[{url:artwork.src,alt:artwork.alt}]:[{url:"/images/hero-history.webp",alt:detail.title}]}};}

export default async function DetailPage({params}:{params:Promise<Params>}){const {locale,type,detail}=await load(await params);const copy=t(locale);const alternate=detail.alternate?alternateApiToPublicPath(detail.alternate.url):null;const canonical=absolutePublicUrl(contentPath(locale,type,detail.slug));const dateRange=formatDateRange(detail,locale);const artwork=contentArtwork(detail.id,locale);
  const artworkCaption=type==="PERSON"?(locale==="vi"?"Chân dung minh họa diễn giải, không phải ảnh tư liệu hay phục dựng khuôn mặt có thẩm quyền.":"Interpretive illustrated portrait, not a documentary photograph or authoritative facial reconstruction."):(locale==="vi"?"Minh họa nguyên bản, không phải ảnh tư liệu lịch sử hay bản sao hiện vật.":"Original illustration, not a historical photograph or artifact reproduction.");
  const jsonLd={"@context":"https://schema.org","@type":"Article",headline:detail.title,description:detail.summary,inLanguage:locale,datePublished:detail.publishedAt,dateModified:detail.updatedAt,url:canonical,author:{"@type":"Organization",name:"Quân Sử Việt"},citation:detail.sources.map((source)=>source.url),about:detail.tags};
  return <PublicShell locale={locale} localeHref={alternate}><main id="noi-dung" className="detail-shell"><JsonLd value={jsonLd}/>
    <nav className="breadcrumbs" aria-label={locale==="vi"?"Đường dẫn":"Breadcrumb"}><Link href={homePath(locale)}>{copy.home}</Link><span>/</span><Link href={contentCollectionPath(locale,type)}>{typeLabel(locale,type)}</Link><span>/</span><span aria-current="page">{detail.title}</span></nav>
    <div className="detail-grid"><article className="detail-article"><p className="eyebrow">{typeLabel(locale,type)}{detail.period?` · ${detail.period.title}`:""}</p><h1>{detail.title}</h1>{artwork?<figure className="detail-art"><Image unoptimized src={artwork.src} alt={artwork.alt} width="1280" height="853" priority decoding="async" data-detail-art={detail.id}/><figcaption>{artworkCaption}</figcaption></figure>:null}<p className="detail-deck">{detail.summary}</p>
      <div className="detail-actions"><CopyLinkButton label={copy.copyLink} copiedLabel={copy.copied}/>{alternate?<Link className="text-link" href={alternate} hrefLang={detail.alternate!.locale}>{detail.alternate!.locale==="en"?copy.readEnglish:copy.readVietnamese}</Link>:null}</div>
      <dl className="detail-pulse">{detail.startDate?<div><dt>{copy.time}</dt><dd>{dateRange}</dd></div>:null}{detail.location?<div><dt>{copy.location}</dt><dd>{detail.location}</dd></div>:null}<div><dt>{detail.lesson&&detail.asOf?copy.lessonAsOf:copy.updated}</dt><dd><time dateTime={detail.lesson&&detail.asOf?detail.asOf:detail.updatedAt}>{formatIsoDate(detail.lesson&&detail.asOf?detail.asOf:detail.updatedAt,locale)}</time></dd></div></dl>
      {detail.lesson?<section className="lesson-content" aria-labelledby="lesson-title"><header className="lesson-heading"><p className="eyebrow">{copy.lessonEyebrow}</p><h2 id="lesson-title">{copy.lessonTitle}</h2><p>{locale==="vi"?"Bài học tách riêng tóm tắt, phân tích, tranh luận và luận điểm có bằng chứng.":"The lesson keeps summary, analysis, debate, and evidenced claims distinct."}</p></header>
        <div className="lesson-intro-grid"><section className="lesson-panel lesson-objectives" aria-labelledby="lesson-objectives-title"><p className="eyebrow">{copy.lessonObjectives}</p><h3 id="lesson-objectives-title">{copy.lessonObjectives}</h3><ul>{detail.lesson.learningObjectives.map((objective)=><li key={objective}>{objective}</li>)}</ul></section><section className="lesson-panel lesson-summary" aria-labelledby="lesson-summary-title"><p className="eyebrow">{copy.lessonSummary}</p><h3 id="lesson-summary-title">{copy.lessonSummary}</h3><p>{detail.lesson.originalSummary}</p></section></div>
        <section className="lesson-panel lesson-analysis" aria-labelledby="lesson-analysis-title"><p className="eyebrow">{copy.lessonAnalysis}</p><h3 id="lesson-analysis-title">{copy.lessonAnalysis}</h3>{detail.lesson.analysis.split(/\n{2,}/).map((paragraph,index)=><p key={index}>{paragraph}</p>)}</section>
        <section className="lesson-panel lesson-debates" aria-labelledby="lesson-debates-title"><p className="eyebrow">{copy.lessonDebates}</p><h3 id="lesson-debates-title">{copy.lessonDebates}</h3><div className="lesson-debate-list">{detail.lesson.debates.map((debate)=><article key={debate.title}><h4>{debate.title}</h4><p>{debate.summary}</p>{debate.claimIds.length?<small>{debate.claimIds.length} {copy.lessonClaims.toLowerCase()}</small>:null}</article>)}</div></section>
        <section className="lesson-panel lesson-claims" aria-labelledby="lesson-claims-title"><p className="eyebrow">{copy.lessonClaims}</p><h3 id="lesson-claims-title">{copy.lessonClaims}</h3>{detail.claims.length?<ol>{detail.claims.map((claim)=><li key={claim.id}><p>{claim.statement}</p><span>{claim.evidence.length} {locale==="vi"?"bằng chứng đã kiểm chứng":"verified evidence item(s)"}</span></li>)}</ol>:<p className="lesson-empty">{copy.lessonNoClaims}</p>}</section>
      </section>:null}
      {detail.lesson ? <ContextualTutor locale={locale} lessonTitle={detail.title} lessonSlug={detail.slug} /> : null}
      <section className="article-copy"><h2>{copy.context}</h2>{detail.body.split(/\n{2,}/).map((paragraph,index)=><p key={index}>{paragraph}</p>)}{detail.result?<><h2>{copy.result}</h2><p>{detail.result}</p></>:null}{detail.role?<dl className="artifact-facts"><div><dt>{locale==="vi"?"Vai trò":"Role"}</dt><dd>{detail.role}</dd></div></dl>:null}{detail.artifactMeta?<dl className="artifact-facts">{Object.entries(detail.artifactMeta).map(([key,value])=><div key={key}><dt>{({category:locale==="vi"?"Phân loại":"Category",holdingPlace:locale==="vi"?"Nơi lưu giữ":"Holding place",material:locale==="vi"?"Chất liệu":"Material"} as Record<string,string>)[key]??key}</dt><dd>{value}</dd></div>)}</dl>:null}</section>
      <section className="sources" id="nguon-tu-lieu" aria-labelledby="sources-title"><div className="section-heading compact-heading"><div><p className="eyebrow">{locale==="vi"?"Kiểm chứng thông tin":"Check the evidence"}</p><h2 id="sources-title">{copy.sources}</h2></div><span className="reviewed-label"><BookIcon/>{copy.reviewed}</span></div><ol>{detail.sources.map((source)=><li key={source.id}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a><span>{[source.author,source.publisher,source.year].filter(Boolean).join(" · ")}</span><small>{locale==="vi"?"Truy cập":"Accessed"} {formatIsoDate(source.accessedAt,locale)}</small></li>)}</ol></section>
    </article><aside className="detail-aside" aria-label={copy.related}>{alternate?<div className="locale-card"><span>{detail.alternate!.locale==="en"?"English edition":"Bản tiếng Việt"}</span><strong>{detail.alternate!.locale==="en"?copy.readEnglish:copy.readVietnamese}</strong><p>{locale==="vi"?"Cùng một nội dung lịch sử, giữ nguyên nguồn đã xuất bản.":"The same historical record with its published sources preserved."}</p><Link href={alternate}>{detail.alternate!.locale==="en"?copy.readEnglish:copy.readVietnamese}</Link></div>:<div className="locale-card unavailable"><strong>{copy.alternateMissing}</strong><p>{locale==="vi"?"Liên kết sẽ xuất hiện khi bản dịch được xuất bản.":"A link will appear after editorial publication."}</p></div>}<h2>{copy.related}</h2><div className="related-list">{detail.related.length?detail.related.map((item)=><ContentCard item={item} locale={locale} variant="compact" key={item.id}/>):<p>{locale==="vi"?"Chưa có nội dung liên quan đã xuất bản.":"No related published content yet."}</p>}</div></aside></div>
  </main></PublicShell>;
}
